# PLAYER CONDUCT

## General.

(a) In addition to any other rights a Team or the NBA may have by contract (including but not limited to the rights set forth in paragraphs 9 and 16 of the Uniform Player Contract) or by law, when a player fails or refuses, without proper and reasonable cause or excuse, to render the services required by a Player Contract or this Agreement, or when a player is, for proper cause, suspended by his Team or the NBA in accordance with the terms of such Contract or this Agreement, the Compensation payable to the player for the year of the Contract during which such refusal or failure and/or suspension occurs may be reduced (or, in the case of a suspension, shall be reduced) as follows:
      (i) By \$2,500 for each of the first two practices missed by the player during any Season, and by \$5,000 per practice for each missed practice thereafter throughout the remainder of that Season;
      (ii) By 1/90th of the player's Current Cash Compensation for each missed Exhibition, Regular Season or Playoff game; and
      (iii) By \$10,000 for each missed promotional appearance required in and in accordance with Article II, Section 8 and paragraph 13(d) of the Uniform Player Contract.

## Mandatory Programs.

If a player fails to attend, without reasonable excuse, a program designated as mandatory by the NBA and the Players Association pursuant to Article XXIX, Section 11, he shall be fined \$10,000 by the NBA; provided, however, that if the player misses the Rookie Transition Program, he shall be suspended for five (5) games.

## Charitable Contributions.

(a) In the event that (i) a fine or suspension is imposed on a player, (ii) such fine or suspension-related Compensation amount is collected by the League, and (iii) the fine or suspension is not grieved pursuant to Article XXXI, then the NBA shall remit fifty percent (50\%) of the amount collected to the National Basketball Players Association Foundation (the "NBPA Foundation") or such other charitable organization selected by the Players Association that qualifies for treatment under Section 501(c)(3) of the Internal Revenue Code of 1986, as now in effect or as it may hereafter be amended (a "Section 501(c)(3) Organization"), and that is approved by the NBA (which approval shall not be unreasonably withheld) (both hereinafter, the "NBPA-Selected Charitable Organization"). The NBA shall remit the remaining fifty percent (50\%) of the amount collected to a Section 501(c)(3) organization selected by the NBA and approved by the Players Association, which approval shall not be unreasonably withheld.
(b) The remittances made by the NBA pursuant to this Section 3 shall be made annually, fifteen (15) days following the end of the NBA Season during which the fine or suspension-related Compensation amount is collected by the NBA. For purposes of this Article and all other provisions of this Agreement, any money remitted or paid to the National Basketball Players Association Foundation by the NBA shall be used for charitable purposes only, and not, for example, for any salaries of Foundation employees or administrative expenses.(c) If a timely Grievance is filed under Article XXXI challenging a fine or suspension of the kind designated in Section 3(a) above, and, following the disposition of the Grievance, the Grievance Arbitrator determines that all or part of the fine or suspension-related amount (plus any accrued interest thereon) is payable by the player to the League, then the League shall remit the amount collected by the League (plus any interest) in accordance with the provisions of Sections 3(a) and (b) above.

## Unlawful Violence.

When a player is convicted of (including a plea of guilty, no contest, or nolo contendere to) a violent felony, he shall immediately be suspended by the NBA for a minimum of ten (10) games.

## Counseling for Violent Misconduct.

(a) In addition to any other rights a Team or the NBA may have by contract or law, when the NBA and the Players Association agree that there is reasonable cause to believe that a player has engaged in any type of off-court violent conduct, the player will (if the NBA and the Players Association so agree) be required to undergo a clinical evaluation by a neutral expert and, if deemed necessary by such expert, appropriate counseling, with such evaluation and counseling program to be developed and supervised by the NBA and the Players Association. For purposes of this paragraph, "violent conduct" shall include, but not be limited to, sexual assault and acts of domestic violence.
(b) Any player who, after being notified in writing by the NBA that he is required to undergo the clinical evaluation and/or counseling program authorized by subsection (a) above, refuses or fails, without a reasonable explanation, to attend or participate in such evaluation and counseling program within seventy-two (72) hours following such notice, shall be fined by the NBA in the amount of \$10,000 for each day following such seventy-two (72) hours that the player refuses or fails to participate in such program.

## One Penalty.

(a) The NBA and a Team shall not discipline a player for the same act or conduct. The NBA's disciplinary action will preclude or supersede disciplinary action by any Team for the same act or conduct.
(b) Notwithstanding anything to the contrary contained in Section 6(a), the same act or conduct by a player may result in both a termination of the player's Uniform Player Contract by his Team and the suspension of the player by the NBA if the egregious nature of the act or conduct is so lacking in justification as to warrant such double penalty.

## League Investigations.

(a) Players are required to cooperate with investigations of alleged player misconduct conducted by the NBA. Failure to so cooperate, in the absence of a reasonable apprehension of criminal prosecution, will subject the player to reasonable fines and/or suspensions imposed by the NBA.
(b) Except as set forth in subsection (c) below, the NBA shall provide the Players Association with such advance notice as is reasonable in the circumstances of any interview or meeting to be held (in person or by telephone) between an NBA representative and a player under investigation by the NBA for alleged misconduct, and shall invite a representative of the Players Association to participate or attend. The failure or inability of a Players Association representative to participate in or attend the interview or meeting, however, shall not prevent the interview or meeting from proceeding as scheduled. A willful disregard by the NBA of its obligation to notify the Players Association as provided for by this Section 7(b) shall bar the NBA from using as evidence against the player in a proceeding involving such alleged misconduct any statements made by the player in the interview or meeting conducted by the NBA representative.(c) The provisions of subsection (b) above shall not apply to interviews or meetings: (i) held by the NBA as part of an investigation with respect to alleged player misconduct that occurred at the site of a game and (ii) which take place during the course of, or immediately preceding or following, such game. With respect to any such interview or meeting, the NBA's only obligation shall be to provide notice to the Players Association that the NBA will be conducting an investigation and holding an interview or meeting in connection therewith. Such notice may be given by telephone at a telephone number, pager number or message-recording number to be designated in writing by the Players Association.

## On-Court Conduct.

In addition to its authority under paragraph 5 of the Uniform Player Contract, the NBA is entitled to promulgate and enforce reasonable rules governing the conduct of players on the playing court that do not violate the provisions of this Agreement. Prior to the date on which any new rule promulgated by the NBA becomes effective, the NBA shall provide notice of such new rule to the Players Association and consult with the Players Association with respect thereto.