# ROOKIE SCALE

## Rookie Scale Contracts for First Round Picks.

(a) Players who: (i) were drafted in the 1995-1997 NBA Drafts; and (ii) signed a Rookie Scale Contract prior to the date of this Agreement, remain subject to the Rookie Scale amounts that were applicable to such players when they were drafted, and such players are not subject to any provisions of this Article VIII.
(b) Except as provided in Sections 2 and 3 below, for players who: (i) are drafted in the 1998-2004 NBA Drafts (and players drafted in the 2005 NBA Draft, if the NBA exercises its option to extend this Agreement pursuant to Article XXXIX); or (ii) were drafted in the 1995-1997 NBA Drafts and who did not sign a Rookie Scale Contract prior to the date of this Agreement, the following rules shall apply to every Rookie Scale Contract for such players:
(c) Each Rookie Scale Contract shall cover a period of three (3) Seasons, but shall have an Option in favor of the Team for the player's fourth Season, as set forth in Article XI, Section 4 below.
(d) A Rookie Scale Contract shall provide in each of the three (3) Seasons covered by the Contract at least 80\% of the applicable Rookie Scale Amount in Current Cash Compensation. Components of Salary in excess of 80\%, if any, are subject to individual negotiation, except that (i) in no event may Salary plus Unlikely Bonuses plus (if earned) any assignment bonus in any Season exceed 120\% of the applicable Rookie Scale Amount, and (ii) a Rookie Scale Contract may not provide for a signing bonus (except for an assignment bonus or "foreign player payments" in excess of \$350,000 made in accordance with Article VII, Section 3(e)) or a loan. A Rookie Scale Contract may provide for a payment schedule in any Season that is more favorable to the player than that called for under paragraph 3 of the Uniform Player Contract, subject to the other provisions of this Agreement.
(e) A First Round Pick who does not sign with the Team that holds his draft rights for any portion of the Season immediately following the Draft in which he was selected shall be treated, for purposes of determining the applicable Rookie Scale Amounts at such time as he enters into a Rookie Scale Contract, as if he were drafted in the Draft immediately preceding the first Season of such Contract at the same draft position at which he was actually selected.
(f) A Rookie Scale Contract must provide for Cash Compensation protection for skill and non-insured injury or illness in each Season to the extent of not less than 80\% of the applicable Rookie Scale Amounts.

## Rookie Contracts for Later-Signed First Round Picks.

Except as provided in Section 3 below, a First Round Pick who does not sign with the Team that holds his draft rights for any portion of the three (3) Seasons following the NBA Draft in which he was selected (and who did not play intercollegiate basketball during such period) may enter into either (i) a Rookie Scale Contract in accordance with Section 1 above, or (ii) if the Team has Room in excess of the applicable first-year Rookie Scale Amount, a Contract covering no fewer than three Seasons that provides for Salary plus Unlikely Bonuses in the first Season up to the amount of the Team's Room and increases or decreases in Salary and Unlikely Bonuses in subsequent Seasons in accordance with Article VII, Section 5(c)(1).

## Loss of Draft Rights.

If for any reason a Team fails to make a Required Tender to a First Round Pick in accordance with Article X, withdraws a Required Tender in accordance with Article X, or renounces a First Round Pick in accordance with Article X, or if a First Round Pick selected in a Subsequent Draft does not sign a Contract for a period of one (1) year following such Subsequent Draft in accordance with Article X, then the rules set forth in Sections 1 and 2 above shall not apply, and such First Round Pick shall become a Rookie Free Agent. In addition, any Team that fails to make a Required Tender to a First Round Pick, withdraws a Required Tender, renounces a First Round Pick, or fails to sign within one (1) year a First Round Pick selected in a Subsequent Draft shall be prohibited from signing such player until after he has signed a Player Contract with another NBA Team, and either (i) the player completes the playing services called for under the Contract, or (ii) the Contract is terminated in accordance with the NBA waiver procedure.