# NBA DRAFT

## Term and Timing of Draft Provisions.

An NBA Draft will be held prior to the commencement of each NBA Season covered by the term of this Agreement and, despite the expiration of the other terms of this Agreement pursuant to Article XXXIX, prior to the commencement of the 2004-05 NBA Season (or, if the NBA exercises its option to extend the Agreement pursuant to Article XXXIX, prior to the commencement of the 2005-06 NBA Season). Each such Draft will be held prior to the July 15 preceding the commencement of the NBA Season on a date to be designated by the Commissioner.

## Number of Choices.

The NBA Draft shall consist of two (2) rounds, with each round consisting of the same number of selections as there will be Teams in the NBA the following Season.

## Negotiating Rights to Draft Rookies.

(a) A Team that drafts a player shall, during the period from the date of such NBA Draft (hereinafter the "Initial Draft") to the date of the next Draft (hereinafter the "Subsequent Draft"), be the only Team with which such player may negotiate or sign a Player Contract, provided that, on or before the July 15 immediately following the Initial Draft (for a First Round Pick), or on or in the two (2) weeks before the September 5 immediately following the Initial Draft (for a Second Round Pick), such Team has made a Required Tender to such player. If a Team has made a Required Tender to such a player and the player has not signed a Player Contract within the period between the Initial Draft and the Subsequent Draft, the Team that drafts the player shall lose its exclusive right to negotiate with the player and the player will then be eligible for selection in the Subsequent Draft.
(b) A Team that, in the Subsequent Draft, drafts a player who (i) was drafted in the Initial Draft, (ii) received a Required Tender from the Team that drafted him in the Initial Draft, and (iii) did not sign a Player Contract with such first Team prior to the Subsequent Draft, shall, during the period from the date of the Subsequent Draft to the date of the next NBA Draft, be the only Team with which such player may negotiate or sign a Player Contract, provided such Team has made a Required Tender. If such player has not signed a Player Contract within the period between the Subsequent Draft and the next NBA Draft with the Team that drafted him in the Subsequent Draft, that Team shall lose its exclusive right, which it obtained in the Subsequent Draft, to negotiate with the player, and the player will become a Rookie Free Agent as of the date of the next NBA Draft.
(c) If a player is drafted in an Initial Draft and (i) receives a Required Tender, (ii) does not sign a Player Contract with a Team prior to the Subsequent Draft, and (iii) is not drafted by any Team in such Subsequent Draft, the player will become a Rookie Free Agent immediately upon the conclusion of the Subsequent Draft.
(d) If a player is drafted by a Team in either an Initial or Subsequent Draft and that Team does not make a Required Tender to such player, the player will become a Rookie Free Agent on the July 16 following such Draft (for a First Round Pick) or on the September 6 following such Draft (for a Second Round Pick).
(e) A Team may at any time withdraw a Required Tender it has made to a player, provided that the player agrees in writing to the withdrawal. In the event that a Required Tender is withdrawn, the player shall thereupon become a Rookie Free Agent.(f) A Team that holds the exclusive rights to negotiate with and sign a drafted player may at any time renounce such exclusive rights, except that, if the Team has made a Required Tender to the player, a renunciation shall not be permitted during the time the player has been given to accept the Required Tender. In order to renounce its exclusive rights with respect to a drafted player, a Team shall provide the NBA with an express, written statement renouncing such exclusive rights. The NBA shall provide a copy of such statement to the Players Association within three (3) business days following its receipt thereof.

## Effect of Contracts with Other Professional Teams.

If a player is drafted by a Team in either an Initial or Subsequent Draft and, during a period in which he may negotiate and sign a Player Contract with only the Team that drafted him, either (i) is a party to a previously existing player contract with a professional basketball team not in the NBA that covers all or any part of the NBA Season immediately following said Initial or Subsequent Draft, or (ii) signs such a player contract, then the following rules will apply:

(a) Subject to subsection (b) below, the Team that drafts the player shall retain the exclusive NBA rights to negotiate with and sign him for the period ending one year from the earlier of the following two dates: (i) the date the player notifies such Team that he is available to sign a Player Contract with such Team immediately, provided that such notice will not be effective until the player is under no contractual or other legal impediment to sign with such Team; or (ii) the date of the NBA Draft occurring in the twelve-month period from September 1 to August 30 in which the player notifies such Team of his availability and intention to play in the NBA during the Season immediately following said twelve-month period, provided that such notice will not be effective until the player is under no contractual or other legal impediment to play with such Team for said Season.
(b) If, by July 1 of any year, the player notifies the Team that has drafted him that by September 1 of such year he will, immediately thereafter or for any future season, be under no contractual or other legal impediment to sign and play with such Team, and provided that on such September 1 the player is in fact under no such contractual or other legal impediment, then, in order to retain the exclusive NBA rights to negotiate with and sign the player as provided in subsection (a), such Team must make a Required Tender to the player by September 5 of such year.
(c) If the player gives the required notice by July 1 of any year, and the Team that drafted him fails to make a Required Tender by September 5 of such year, the player shall thereupon become a Rookie Free Agent.
(d) If, during the one-year period of exclusive NBA negotiating rights set forth in subsection (a) above, the player signs a player contract with a professional basketball team not in the NBA and (i) the player has not made a bona fide effort to negotiate a Player Contract with the Team possessing his exclusive NBA rights or (ii) such bona fide effort is made and such Team makes a Required Tender to such player in accordance with subsection (b) above, then such Team shall retain the exclusive NBA rights to negotiate with and sign the player for additional one-year periods as measured in and in accordance with the provisions of subsection (a).
(e) If, during the one-year period of exclusive NBA negotiating rights set forth in subsection (a) above, the player signs a player contract with a professional basketball team not in the NBA and (i) the player has made a bona fide effort to negotiate a Player Contract with the Team possessing his exclusive NBA rights, and (ii) such Team fails to make a Required Tender to such player in accordance with subsection (b) above, then in no event shall said exclusive NBA rights be retained.
(f) If, during the one-year period of exclusive NBA negotiating rights set forth in subsection (a) above, the Team makes or has made a Required Tender to the player and the player does not sign a player contract with any professional basketball team, then (i) in the case of a player who was previously drafted in an Initial Draft, the next NBA Draft following such one-year period shall be deemed the Subsequent Draft as to such player, and the rules applicable to a player who is subject to a Subsequent Draft will apply, or (ii) in the case of a player who was previously drafted in a Subsequent Draft, such player shall become a Rookie Free Agent at the end of such one-year period.
(g) Notice under this Section 4 shall be provided in writing by personal delivery or prepaid certified, registered, or overnight mail sent to the Team's principal address or principal office (as then listed in the NBA's records), to the attention of the Team's general manager. For purposes of this Section 4, a "professional basketball team" shall mean any team in any country that pays money or compensation of any kind (in excess of a stipend for living expenses) to a basketball player for rendering services for such team.

## Application to Players with Remaining Intercollegiate Eligibility.

(a) A person residing within the United States whose high school class has graduated shall become eligible to be selected in an NBA Draft if he renounces his intercollegiate basketball eligibility by written notice to the NBA at least forty-five (45) days prior to such Draft. If such person is selected in such Draft by a Team, the following rules apply:
    (i) Subject to Section 5(b) below, if the player does not thereafter play intercollegiate basketball, then the Team that drafted him shall, during the period from the date of such Draft to the date of the Draft in which the player would, absent renunciation of intercollegiate eligibility, first have been eligible to be selected, be the only Team with which the player may negotiate or sign a Player Contract, provided that such Team makes a Required Tender to the player each year. For purposes hereof, the Draft in which such player would, absent renunciation of such intercollegiate eligibility, first have been eligible to be selected, will be deemed the "Subsequent Draft" as to that player, and the rules applicable to a player who has been drafted in a Subsequent Draft will apply. If the player, having been selected in a Draft for which he was eligible by virtue of renunciation of intercollegiate eligibility, has not signed a Player Contract with the Team that drafted him in such Draft following a Required Tender by that Team and is not drafted in the Subsequent Draft (as defined in the previous sentence), he shall become a Rookie Free Agent.
    (ii) If the player does thereafter play intercollegiate basketball, then the Team that drafted him shall retain the exclusive NBA rights to negotiate with and sign the player for the period ending one year from the date of the Draft in which the player would, absent renunciation of intercollegiate eligibility, first have been eligible to be selected, provided that such Team makes a Required Tender to the player each year. For purposes hereof, the Draft in which such player would, absent renunciation of intercollegiate eligibility, first have been eligible to be selected, will be deemed the "Initial Draft" as to that player. The next NBA Draft shall be deemed the "Subsequent Draft" as to that player, and the rules applicable to a player who has been drafted in a Subsequent Draft will apply.
(b) A person residing within the United States whose high school class has graduated, who is not yet eligible to be selected in an NBA Draft, and who signs a player contract with a professional basketball team not in the NBA, shall thereupon become eligible to be selected in the next NBA Draft, and if so selected, shall be treated as though he were a player referred to in Section 4 above. For purposes of this subsection, a "professional basketball team" shall mean any team in any country that pays money or compensation of any kind (in excess of a stipend for living expenses) to a basketball player for rendering services to such team.

## Application to Foreign Players.

(a) For purposes of this Section, a "foreign player" shall mean any person residing outside of the United States who participates in the game of basketball as an amateur or as a professional.
(b) A foreign player is eligible to be selected in an NBA Draft held during the calendar year in which such player has his twenty-second (22nd) birthday. Any foreign player who is older than twenty-two (22), and who was not selected in the NBA Draft held during the calendar year of his twenty-second (22nd) birthday, is a Rookie Free Agent.
(c) Notwithstanding subsection (b) above, a foreign player who is at least eighteen (18) years old and who has not exercised intercollegiate basketball eligibility in the United States shall become eligible to be selected in an NBA Draft held prior to the calendar year in which he has his twenty-second (22nd) birthday if he expresses his desire to become eligible to be selected in the next NBA Draft by written notice to the NBA at least forty-five (45) days prior to such Draft.
(d) A foreign player who exercises intercollegiate basketball eligibility in the United States during the season prior to an NBA Draft shall be subject to the rules regarding completion or renunciation of collegiate eligibility, as set forth in Section 5 above.

## Assignment of Draft Rights.

In the event that the exclusive right to negotiate with a player obtained in any NBA Draft is assigned by a Team to another Team, in accordance with NBA procedures, the Team to which such right has been assigned shall have the same, but no greater, right to negotiate with and sign such player as possessed by the Team assigning such right, and such player shall have the same, but no greater, obligation to the Team to which such right has been assigned as he had to the Team assigning such right.

## General.

(a) The placement of a Rookie on the Armed Services List, or on any of the other lists described in the NBA By-Laws, or on any other list created by the NBA, shall not extend the period of exclusive negotiating rights which a Team has to any Draft Rookie beyond the period specified in this Agreement.
(b) Nothing contained herein shall prevent the NBA, in accordance with the applicable provisions of the NBA Constitution and By-Laws, from prohibiting or otherwise responding to violations by Teams of the exclusive NBA rights obtained in any NBA Draft, as set forth or referred to in this Article. Other than as specifically agreed to herein, nothing contained in this Agreement shall be deemed to be an agreement by the Players Association to any provision of the NBA Constitution and By-Laws.
(c) A person who has renounced his intercollegiate eligibility and expressed his desire to become eligible to be selected in the next NBA Draft pursuant to Section 5 or Section 6 above shall be entitled to withdraw from such Draft by providing written notice that is received by the NBA seven days prior to such Draft.
(d) Any claim by a player that a Contract offered as a Required Tender pursuant to this Article X fails to meet one or more of the criteria for a Required Tender shall be made by written notice to the Team (with copies sent to the NBA and the Players Association), no later than ten (10) days after the receipt of such Contract by the Players Association. Such notice must set forth the specific changes that the player asserts must be made to the offered Contract in order for it to constitute a Required Tender. Upon receipt of such notice, if the requested changes are necessary to satisfy the requirements of a Required Tender, the Team may within five (5) business days offer the player an amended Contract incorporating the requested changes. If the Team offers such an amended Contract, the player shall be precluded from asserting that such Contract does not constitute a timely
and valid Required Tender.
(e) For purposes of this Article X, any rights afforded to "a Team that drafts a player" shall also be afforded to any Team to which such rights are subsequently assigned.