# FREE AGENCY

## General Rules.

(a) Subject to the provisions of Article VII, including, but not limited to, Article VII, Section 6(b): (i) an Unrestricted Free Agent is free at any time after July 1 to negotiate, and free at any time after August 1 to enter into, a Player Contract with any Team; and (ii) a Restricted Free Agent is free at any time after July 1 to negotiate a Player Contract with his Prior Team, to accept a Qualifying Offer from his Prior Team, and to negotiate an Offer Sheet with any Team other than his Prior Team, and is free at any time after August 1 to enter into a Player Contract with his Prior Team or an Offer Sheet with any Team other than his Prior Team.
(b) No compensation obligation of any kind to another Team shall be applicable to any Free Agent. No right of first refusal of any kind shall be applicable to any Free Agent other than a Restricted Free Agent.

## No Individually-Negotiated Right of First Refusal.

(a) No Player Contract, or any Renegotiation, Extension, or other amendment of a Player Contract, executed after the date of this Agreement, may include any individually negotiated right of first refusal or other limitation on player movement following the last Salary Cap Year covered by such Player Contract.
(b) No right of first refusal rule, practice, policy, regulation or agreement providing for a right of first refusal shall be applied to any player as a result of that player's entry into a player contract with or the playing with any team in any professional basketball league other than the NBA.

## Withholding Services.

A player who withholds playing services called for by a Player Contract for more than thirty (30) days after the start of the last Season covered by his Player Contract shall be deemed not to have "complet[ed] his Player Contract by rendering the playing services called for thereunder." Accordingly, such a player shall not be a Veteran Free Agent and shall not be entitled to negotiate or sign a Player Contract with any other professional basketball team unless and until the Team for which the player last played expressly agrees otherwise.

## Fourth Year Option for First Round Picks.

(a) For First Round Picks who (i) are drafted in the 1998-2004 NBA Drafts (or are drafted in the 2005 NBA Draft, if the NBA exercises its option to extend this Agreement pursuant to Article XXXIX); or (ii) were drafted in the 1995-1997 NBA Drafts and who do not sign a Rookie Scale Contract until after the date of this Agreement: if the Team that drafted the player (or a Team to which the player has been assigned) has exercised its Fourth Year Option (as described in subsection (b) below) to such player on or before the October 31 following the second Season of such player's Rookie Scale Contract with the Team, then such Team shall be deemed to have exercised the Option Year of the player's Rookie Scale Contract, to cover the Season immediately following the first three Seasons of such player's Rookie Scale Contract, on the terms and conditions contained therein in accordance with subsection (b) below.
(b) The Fourth Year Option Notice shall be a notice to the player that is either personally delivered to the player or his representative or sent by prepaid certified, registered, or overnight mail to the last known address of the player or his representative, signed by the Team, informing the player that the Team has exercised its Option for the player's fourth NBA Season ("Fourth Year Option"). The terms and conditions that apply to the Option Year shall be unchanged from all terms and conditions that applied to the player's third NBA Season (including but not limited to Cash Compensation protection), except that the Salary for the Option Year shall be increased over the Salary for his third Season by the applicable percentage specified in Exhibit B hereto.
(c) If a Team has not delivered a Fourth Year Option Notice by the specified deadline, the player shall, following his third NBA Season, become an Unrestricted Free Agent.

## Qualifying Offers to Make Certain Players Restricted Free Agents.

(a) From the day following a Season covered by a Fourth Year Option through the immediately following June 30, the player's Team may make a Qualifying Offer to the player covered by such Option. If such a Qualifying Offer is made, then, on the July 1 following the Season covered by the player's Fourth Year Option, the player shall become a Restricted Free Agent, subject to a Right of First Refusal in favor of the Team ("ROFR Team"), as set forth in Section 6 below. If such a Qualifying Offer is not made, then the player shall become an Unrestricted Free Agent on such July 1.
(b) Beginning with the 1999-2000 Salary Cap Year, any Veteran Free Agent whose first Season in the NBA was the 1998-99 Season or later (other than a Veteran Free Agent whose Fourth Year Option was not exercised), and who will have three (3) or fewer Years of Service as of the June 30 following the end of the last Season covered by his Player Contract, will be a Restricted Free Agent if his Prior Team makes a Qualifying Offer to the player at any time from the day following such Season through the immediately following June 30. If such a Qualifying Offer is made, then, on the July 1 following the last Season covered by the player's Player Contract, the player shall become a Restricted Free Agent, subject to a Right of First Refusal in favor of the Team ("ROFR Team"), as set forth in Section 6 below. If such a Qualifying Offer is not made, then the player shall become an Unrestricted Free Agent on such July 1.
(c) A Qualifying Offer made to a Restricted Free Agent may be withdrawn at any time up to the following August 7. If the Qualifying Offer is not withdrawn by August 7, it must thereafter remain open until the following October 1. If a Qualifying Offer is withdrawn, the player shall immediately become an Unrestricted Free Agent. However, a player who knows that he has a physical disability that would render him physically unable to perform the playing services required under a Player Contract the following Season may not validly accept a Qualifying Offer received under this Section 5 or Section 6 below, unless the ROFR Team consents after disclosure of such physical disability. Notwithstanding the immediately preceding sentence, a player who knows that he has a physical disability that would render him physically unable to perform the playing services required under a Player Contract the following Season remains subject to the ROFR Team's Right of First Refusal.
(d) Any claim that a Contract offered as a Qualifying Offer fails to meet one or more of the criteria for a Qualifying Offer shall be made by notice to the Team, in writing, no later than ten (10) days after a copy of the Qualifying Offer was given by the Team or the NBA to the Players Association. Such notice must set forth the specific changes that allegedly must be made to the offered Contract in order for it to constitute a Qualifying Offer. Upon receipt of such notice, if the requested changes are necessary to satisfy the requirements of a Qualifying Offer, the Team may, within five (5) business days, offer the player an amended Contract incorporating the requested changes. If the Team offers such an amended Contract, the player and the Players Association shall be precluded from asserting that such Contract does not constitute a timely and valid Qualifying Offer.

## Restricted Free Agency.

(a) If a Restricted Free Agent does not sign an Offer Sheet with any Team by March 1 of the NBA Season for which the Qualifying Offer is made, and does not sign a Player Contract with the ROFR Team before that Season ends, then his ROFR Team may reassert its Right of First Refusal for the following NBA Season by extending another Qualifying Offer (on the same terms as the prior Qualifying Offer) by the next July 1. A ROFR Team may continue to reassert its Right of First Refusal by following the foregoing procedure in each subsequent year in which that Restricted Free Agent does not sign an Offer Sheet with any Team by March 1 of the NBA Season for which the Qualifying Offer is made, and does not sign a Player Contract with the ROFR Team before that Season ends.
(b) When a Restricted Free Agent receives an offer to sign a Player Contract from a Team (the "New Team") other than the ROFR Team, which he desires to accept, he shall give to the ROFR Team a completed certificate substantially in the form of Exhibit G annexed hereto (the "Offer Sheet"), signed by the Restricted Free Agent and the New Team, which shall have attached to it a Uniform Player Contract separately specifying: (i) the "Principal Terms" (as defined in Subsection 6(c) below) of the New Team's offer; and (ii) any non-Principal Terms of the New Team's offer that the ROFR Team is not required to match (as specified in Subsection 6(c) below) but which would be included in the player's Player Contract with the New Team if the ROFR Team does not exercise its Right of First Refusal. The Offer Sheet must be for a Player Contract with a term of more than two NBA seasons (not including any Option Year). In order to extend an Offer Sheet, the New Team must have Room for the player's Player Contract at the time the Offer Sheet is signed. The ROFR Team, upon receipt of the Offer Sheet, may exercise its Right of First Refusal, which shall have the consequences hereinafter set forth below in this Section 6.
(c) The Principal Terms of an Offer Sheet shall not include any Non-Cash Compensation. In addition, the Principal Terms of an Offer Sheet are only:
    (i) the fixed and specified Cash Compensation that the New Team will pay or lend to the Restricted Free Agent and/or his designees as a signing bonus, Current Cash Compensation, and/or Deferred Cash Compensation in specified installments on specified dates;
    (ii) Incentive Compensation payable in cash; provided, however, that the only elements of such Incentive Compensation that shall be included in the Principal Terms are the following: (A) bonuses that qualify as Likely Bonuses based upon the performance of the Team extending the Offer Sheet and the ROFR Team; and (B) generally recognized league honors to be agreed upon by the Players Association and the NBA; and
    (iii) Any allowable amendments to the terms contained in the Uniform Player Contract (e.g., Cash Compensation protection, Early Termination Options, assignment bonuses).
(d) If, within fifteen (15) days from the date it receives an Offer Sheet, the ROFR Team gives to the Restricted Free Agent a "First Refusal Exercise Notice" substantially in the form of Exhibit H annexed hereto, such Restricted Free Agent and the ROFR Team shall be deemed to have entered into a Player Contract containing all the Principal Terms included in the Uniform Player Contract attached to the Offer Sheet.
(e) If the ROFR Team does not give the First Refusal Exercise Notice within the aforementioned fifteen (15) day period, the player and the New Team shall be deemed to have entered into a Player Contract containing all of the terms and conditions included in the Uniform Player Contract attached to the Offer Sheet.
(f) After exercising its Right of First Refusal as described in this Section 6, the ROFR Team may not trade the Restricted Free Agent for one (1) year, without the player's consent. Even with the player's consent, for one (1) year, neither the ROFR Team exercising its Right of First Refusal nor any other Team may trade the player to the Team whose Offer Sheet was matched.
(g) Any Team that exercises its Right of First Refusal may do so subject to the player's passing a physical examination to be conducted by the Team within five (5) days from its exercise of the Right of First Refusal. In the event the player does not pass the physical examination, the ROFR Team may withdraw its First Refusal Exercise Notice within five (5) days of such examination; however, the New Team may not withdraw the previously submitted Offer Sheet. In the event the player, after being given reasonable advance notice, does not submit to a requested physical examination within five (5) days of the exercise of the Right of First Refusal then, until such time as the player submits to the requested physical examination, the ROFR Team may withdraw its First Refusal Exercise Notice, which shall have the effect of invalidating the Offer Sheet and causing the Team that issued the Offer Sheet to be prohibited from signing or acquiring the player for a period of one (1) year from the date the First Refusal Exercise Notice was withdrawn.
(h) There may be only one Offer Sheet signed by a Restricted Free Agent outstanding at any one time, provided that the Offer Sheet has also been signed by a Team. An Offer Sheet, both before and after it is given to the ROFR Team, may be revoked or withdrawn only upon the written consent of the ROFR Team, the New Team and the Restricted Free Agent. In such event, a Restricted Free Agent shall again be free to negotiate and sign an Offer Sheet with any Team, and any Team shall again be free to negotiate and sign an Offer Sheet with such Restricted Free Agent, subject only to the ROFR Team's renewed Right of First Refusal.
(i) An expedited arbitration before the System Arbitrator, whose decision shall be final and binding upon all parties, shall be the exclusive method for resolving any disputes concerning this Section. If a dispute arises between the player and either the ROFR Team or the New Team, as the case may be, relating to the contents of an Offer Sheet, and/or whether the binding agreement is between the Restricted Free Agent and the New Team or the Restricted Free Agent and the ROFR Team, such dispute shall immediately be submitted to the System Arbitrator, who shall resolve such dispute within five (5) days.
(j) A Restricted Free Agent may not give an Offer Sheet to the ROFR Team at any time after the March 1 of the Season for which he has been made a Qualifying Offer.
(k) On the same day as the giving of an Offer Sheet to the ROFR Team, the ROFR Team shall cause a copy thereof to be given to the NBA, which shall cause a copy thereof to be promptly given to the Players Association. On the same day as the giving of a First Refusal Exercise Notice to the Restricted Free Agent, the Restricted Free Agent shall cause a copy thereof to be given to the New Team, which shall cause a copy thereof to be promptly given to the NBA, which shall cause a copy thereof to be promptly given to the Players Association.
(l) There may be no consideration of any kind given by one Team to another Team in exchange for a Team's decision to exercise or not to exercise its Right of First Refusal, or in exchange for a Team's decision to submit or not to submit an Offer Sheet to a Restricted Free Agent.
(m) Any Offer Sheet, First Refusal Exercise Notice or other writing required or permitted to be given under this Section 6, shall be either by personal delivery or by prepaid certified, registered or overnight mail addressed as follows:
     
     To any NBA Team: addressed to that Team at the principal address of such Team as then listed on the records of the NBA or at the Team's principal office, to the attention of the Team's general manager;
     
     To the NBA: National Basketball Association, Olympic Tower, 645 Fifth Avenue, New York, NY 10022, Att: General Counsel;
     
     To the Players Association: National Basketball Players Association, 1700 Broadway, Suite 1400, New York, NY 10019, Att: Counsel.
     
     To a Restricted Free Agent: to his address listed on the Offer Sheet and, if the Restricted Free Agent designates a representative on the Offer Sheet and lists such representative's address thereof, a copy shall be sent to such representative at such address.
(n) An Offer Sheet shall be deemed given only when actually received by the ROFR Team. A First Refusal Exercise Notice shall be deemed given when sent by the ROFR Team. A Qualifying Offer shall be deemed given when sent by the ROFR Team. Other writings required or permitted to be given under this Section 6 shall be deemed given only when actually received by the party to whom addressed.