# MEDICAL TREATMENT OF PLAYERS AND RELEASE OF MEDICAL INFORMATION
\chaptermark{MEDICAL TREATMENT OF \ldots}

## One Surgeon.

Each Team agrees that a player requiring the care and treatment of an orthopedic surgeon will, so far as practicable, be referred to and treated by one orthopedic surgeon (rather than several).

## Committee of Team Physicians.

Representatives designated by the Players Association shall participate in meetings of the committee of Team physicians appointed by the NBA for the purpose of discussing matters related to the medical care and treatment of players.

## Public Release of Medical Information.

(a) Subject to subsection (b) below, each Team may make public medical information relating to the players in its employ, provided that such information relates solely to the reasons why any such player has not been or is not rendering services as a player.
(b) A player or his immediate family (where appropriate) shall have the right to approve the terms and timing of any public release of medical information relating to any injuries or illnesses suffered by that player that are potentially life- or career-threatening, or that do not arise from the player's participation in NBA games or practices.

## Non-Team Physicians.

A player who consults a physician other than such player's Team physician shall give notice of such consultation to his Team's physician and shall authorize and direct such other physician to provide his Team with all information it may request concerning any condition that, in the judgment of the Team's physician, may affect such player's ability to play skilled basketball.

## Arbitration Proceedings.

During the course of any arbitration proceeding, the Grievance Arbitrator may, by appropriate process, require any person (including, but not limited to, a Team and a Team physician, and a player and any physician consulted by such player) to provide to the player or that player's Team, as the case may be, all medical information in the possession of any person relating to the subject matter of the arbitration.

## Draftees.

Prior to any NBA Draft, the NBA and/or its Teams acting jointly may request that persons eligible for such Draft voluntarily submit to the administration of standardized medical or laboratory tests (other than tests for controlled substances), the results of which shall be made available to any Team upon request, but which shall be kept confidential from the public and the media. Any person who submits to the administration of such tests may, prior to such Draft, be requested to submit voluntarily to an examination by the physician(s) for an NBA Team(s), but shall not be requested to undergo any medical or laboratory test administered at the request of the NBA and/or its Teams.