# PROHIBITION OF NO-TRADE CONTRACTS

## General Limitation.

No Player Contract may contain any prohibition or limitation of an NBA Team's right to assign such Contract to another NBA Team.

## Exceptions to General Limitation.

Notwithstanding the provisions of Section 1 of this Article XXIV:

(a) A Player Contract may contain (in Exhibit 4 to such Player Contract) a provision entitling a Player to earn, on a one-time basis, upon the first assignment of that Player Contract, a specific sum of money that does not exceed 15\% of the Compensation remaining to be earned by the Player pursuant to that Player Contract at the time of such first assignment; provided, however, that any such payment must be made within thirty (30) days of the date of the first assignment of the Contract.
(b) A Player Contract entered into by a player who has eight (8) or more Years of Service in the NBA and who has rendered four (4) or more Years of Service for the Team entering into such Contract may contain a prohibition or limitation of such Team's right to assign such Contract to another NBA Team.