# NO-STRIKE AND NO-LOCKOUT PROVISIONS AND OTHER UNDERTAKINGS
\chaptermark{NO-STRIKE AND NO-LOCKOUT \ldots}

## No Strike.

During the term of this Agreement, neither the Players Association nor its members shall engage in any strikes, cessations or stoppages of work, or any other similar interference with the operations of the NBA or any of its Teams.

## No Lockout.

During the term of this Agreement, neither the NBA nor its Teams shall engage in any lockouts, cessations or stoppages of work or any other similar interference with the employment of NBA players by NBA Teams.

## No Breach of Player Contracts.

The Players Association agrees that it will not engage in any concerted activities to breach, induce the breach of, or threaten to breach or induce the breach of, any Player Contract.

## Best Efforts of Players Association.

The Players Association will use its best efforts to prevent each player from rendering, or threatening to render, services as a professional basketball player for another professional basketball team during the term of a Player Contract between such player and the Team for which he plays (except as said Player Contract may be assigned, sold, or transferred in accordance with the provisions thereof); to prevent each player from refusing, or threatening to refuse, to participate in any scheduled Exhibition game, Regular Season game, All-Star Game, Rookie All-Star Game, All-Star Skills Competition, or Playoff game; to prevent each player from otherwise breaching, or threatening to breach, such Player Contract; and to prevent each player from making any demand upon the NBA or any of its Teams, including, but not limited to, a demand (accompanied by threats that the player will render services as a professional basketball player for another professional basketball team during the term of such Player Contract) that such Player Contract be renegotiated during the term thereof; provided, however, that this provision is not intended to prevent any player from entering into negotiations with a Team, in accordance with Article VII, with respect to the compensation to be paid to said player for the Season(s) following the last playing Season covered by any Player Contract, or renewal or extension thereof.

## Player's Threat to Withhold Services.

The NBA and the Players Association agree that a player who publicly demands a renegotiation of his Player Contract, and who threatens to withhold the services he has agreed to render under such Player Contract or to perform at a level below his full capabilities unless such renegotiation takes place, shall be considered to have engaged in conduct impairing the faithful and thorough discharge of the duties incumbent upon the player within the meaning of paragraph 5 of the Uniform Player Contract.

## No Negotiations with Other Teams While Under Contract.

Except as permitted in accordance with Article XI (Free Agency), no player who is a party to a Player Contract with a Team shall, during the term of such Contract (including any permissible option year), enter into negotiations with another Team.