# GRIEVANCE AND ARBITRATION PROCEDURE

## Scope.

(a) Any dispute (such dispute hereinafter being referred to as a "Grievance") involving the interpretation or application of, or compliance with, the provisions of this Agreement or the provisions of a Player Contract (except as provided in paragraph 9 of a Uniform Player Contract), including a dispute concerning the validity of a Player Contract, shall be resolved exclusively by the Grievance Arbitrator in accordance with the procedures set forth in this Article; provided, however, that disputes arising under Articles VII, VIII, X, XI, XII, XIII, XIV, XV, XVI, XXXVII, XXXIX, and XL shall (except as otherwise specifically provided by Article VII, Section 3(d)(5) above) be determined by the System Arbitrator provided for in Article XXXII.
(b) The Grievance Arbitrator shall also have jurisdiction over disputes involving player discipline to the extent set forth in Section 8 below and over disputes concerning the disposition of funds deposited in accordance with Section 9 below to the extent set forth in that Section.

## Initiation.

(a) Grievances may be initiated, as set forth below, by a player, a Team, the NBA, or the Players Association, except that the Players Association may not initiate a Grievance involving player discipline without the approval of the player(s) concerned.
(b) No party may initiate a Grievance until and unless it has first discussed the matter with the party or parties against whom the Grievance is to be initiated in an attempt to settle it.
(c) A Grievance must be initiated within thirty (30) days from the date of the occurrence upon which the Grievance is based, or within thirty (30) days from the date upon which the facts of the matter became known or reasonably should have become known to the party initiating the Grievance, whichever is later.
(d) Subject to the provisions of Sections 2(a)-(c) above, (i) a player or the Players Association may initiate a Grievance by filing written notice thereof with a Team and furnishing a copy of such notice to the NBA; (ii) a Team may initiate a Grievance by filing written notice thereof with the Players Association and furnishing copies of such notice to the player(s) involved and to the NBA; and (iii) the NBA may initiate a Grievance by filing written notice thereof with the Players Association and furnishing copies of such notice to the player(s) and Team(s) involved.

## Hearings.

(a) Upon at least thirty (30) days' written notice to the other side, the NBA and the Players Association may arrange to have a hearing scheduled on a date that is mutually convenient to the parties to the dispute, the NBA, the Players Association, and the Grievance Arbitrator; provided, however, that if the NBA and the Players Association cannot agree on a hearing date, the Grievance Arbitrator shall set a reasonable hearing date that follows the expiration of the 30-day notice period. Only the NBA and the Players Association may schedule or postpone hearings with the Grievance Arbitrator.
(b) Notwithstanding the provisions of Section 3(a), during each Salary Cap Year covered by this Agreement, the Players Association and the NBA shall each have the right, upon a showing of need, to have two (2) Grievances scheduled for hearing on or after the tenth day following service of the notice provided for by Section 3(a). The provisions of this subsection (b) shall not limit or otherwise affect the rights of the NBA or the Players Association pursuant to Section 12 of this Article XXXI.
(c) If a Grievance is scheduled for hearing under Section 3(a) or 3(b) above and the hearing date is thereafter postponed by either the NBA or the Players Association, the postponement fee (if any) of the Arbitrator will be borne by the postponing party unless that party objects and the Arbitrator finds that the postponement was for good cause. Should good cause be found, the parties will share any postponement costs equally.
(d) In any Grievance matter, neither the NBA nor the Players Association may request or be granted more than one postponement of a hearing previously scheduled under Sections 3(a) or (b) above. If, after postponing such a hearing, a party fails to attend a second scheduled hearing in the same Grievance matter, the Grievance shall be resolved against that party.
(e) If a hearing on a Grievance initiated after the execution of this Agreement is not scheduled to take place within one (1) year of the filing of the Grievance, or, in the case of a postponement of the first hearing date by the opposing party, if a second hearing in that Grievance is not scheduled to take place within two (2) years of the filing of the Grievance, the Grievance shall be dismissed with prejudice.
(f) Any Grievance filed prior to the execution of this Agreement shall be dismissed with prejudice unless the NBA or the Players Association, as the case may be, schedules a hearing under Sections 3(a) or (b) above to take place within six (6) months of the execution of this Agreement.
(g) For purposes of computing time under this Section 3, the time shall be tolled during any period when there is no Grievance Arbitrator or when the grieving party has been unable to schedule a hearing (after making efforts to do so) because the Grievance Arbitrator is unavailable.
(h) Hearings before the Grievance Arbitrator shall be held in New York (alternating between the NBA and Players Association offices). All such hearings shall be conducted in accordance with the Labor Arbitration Rules of the American Arbitration Association; provided, however, that in the event of any conflict between such Rules and the provisions of this Agreement, the provisions of this Agreement shall control.

## Procedure.

(a) Not later than seven (7) days prior to the hearing, the parties shall submit to the Grievance Arbitrator a joint statement of the issue(s) in dispute. If the parties cannot agree on such a joint statement, they shall each submit separate statements setting forth the disputed issue(s).
(b) Not later than three (3) business days prior to the hearing, the parties shall exchange witness lists, relevant documents and other evidentiary materials, and citations of legal authorities that each side intends to rely on in its affirmative case. Absent a showing of good cause, no party may proffer, refer to, or rely on the testimony of any witness, any document or other evidentiary material in its affirmative case that has not been identified to the other side as required by this subsection.
(c) The Grievance Arbitrator shall grant the request of any party to file a pre-hearing and/or post-hearing brief, unless the opposing party demonstrates that the filing of briefs is unreasonable in the circumstances.

## Arbitrator's Decision and Award.

(a) Except as set forth in Section 12 below, the Grievance Arbitrator shall render an Award as soon as practicable. That Award may be accompanied by a written opinion, or the written opinion may follow within a reasonable time thereafter. In no event shall the Award or any written opinion be issued more than thirty (30) days following the conclusion of a Grievance hearing (or the submission of post-hearing briefs where applicable). The Award shall constitute full, final and complete disposition of the Grievance, and shall be binding upon the player(s) and Team(s) involved and the parties to this Agreement.
(b) The Grievance Arbitrator shall have jurisdiction and authority only to: (i) interpret, apply, or determine compliance with the provisions of this Agreement; (ii) interpret, apply or determine compliance with the provisions of Player Contracts; (iii) determine the validity of Player Contracts pursuant to Section 1 of this Article; (iv) award damages in connection with a proceeding provided for in Section 11 below; (v) award declaratory relief in connection with a proceeding initiated by a Team to determine whether such Team may properly terminate a Player Contract pursuant to paragraph 16(a) of such Contract, and what, if any, liability such Team would incur as a result of such termination; and (vi) resolve disputes arising under Article VII, Section 3(d)(5), Article XXII, Section 5, Article XXVI, and Article XXXIII in the manner set forth therein. The Grievance Arbitrator shall not have jurisdiction or authority to add to, detract from, or alter in any way the provisions of this Agreement (including the provisions of this subsection) or any Player Contract. Nor, in the absence of agreement by the NBA and the Players Association, shall the Grievance Arbitrator have jurisdiction or authority to resolve questions of substantive arbitrability.
(c) In any Grievance that involves an action taken by the Commissioner (or his designee) concerning (i) the preservation of the integrity of, or the maintenance of public confidence in, the game of basketball, and (ii) a fine and/or suspension that results in a financial impact to the player of more than \$25,000, the Grievance Arbitrator shall apply an "arbitrary and capricious" standard of review.

## Grievance Arbitrator.

The parties to this Agreement shall agree upon the appointment of a new Grievance Arbitrator, who shall serve for the duration of this Agreement; provided, however, that as of September 1, 1999, and as of each successive September 1, either of the parties to this Agreement may discharge the Grievance Arbitrator by serving thirty (30) days' prior written notice upon him and upon the other party to this Agreement; and provided, further, that as of the April 30 of the last Season covered by this Agreement, either of the parties may discharge the Grievance Arbitrator by serving thirty (30) days' prior written notice upon him and upon the other party to this Agreement. If the Grievance Arbitrator is discharged, the parties shall thereupon either agree upon a successor Grievance Arbitrator or select a successor from an American Arbitration Association list of prominent professional arbitrators, alternately striking names from such list until only one remains; provided, however, that if the Grievance Arbitrator is discharged as of the April 30 of the last Season covered by this Agreement, the parties shall, if a successor Grievance Arbitrator is not agreed upon by June 1 of such Season, select such successor from an American Arbitration Association list (by alternatively striking names) no later than June 20. A Grievance Arbitrator who is discharged shall continue to serve until his successor is agreed upon or selected. The same procedures shall be followed if the parties cannot agree upon the initial Grievance Arbitrator within thirty (30) days from the date of this Agreement.

## Injury Grievances.

(a) Disputes arising under paragraphs 7, 16(a)(iii), 16(b), or 16(c) of a Uniform Player Contract as to (i) whether a player was in sufficiently good condition to play skilled basketball, (ii) whether the player was injured as a direct result of participating in any basketball practice or game played for the Team, (iii) whether such injury disabled the player and/or rendered him unfit to play skilled basketball, (iv) whether, at the time of termination pursuant to paragraph 16(a)(iii), the player was unfit to play skilled basketball as the result of an injury resulting directly from his playing for the Team and, if so, the duration of such unfitness, and/or (v) whether the player is being asked to submit to appropriate medical treatment shall be processed and determined in the same manner as a Grievance under Sections 2-6 above, except that if a party to such Grievance so elects, the NBA and the Players Association shall agree upon a neutral physician or (in the absence of such agreement) jointly request that the President of the American College of Orthopedic Surgeons (or such other similar organization as the parties agree may be most appropriate to the issues in dispute) designate a physician who has no relationship with any party covered by this Agreement to conduct a physical examination of the player and to perform the functions of the Grievance Arbitrator. The physician so selected shall render a written decision which shall constitute full, final and complete disposition of the dispute, and shall be binding upon the player(s) and Team(s) involved and the parties to this Agreement. Any fees or costs associated with the physician's determination will be borne equally by both sides.
(b) All other disputes arising under paragraphs 7, 16(a)(iii), 16(b), or 16(c) of a Uniform Player Contract (including, but not limited to, a dispute as to whether the suspension of a player or the termination of a Player Contract was by reason of a disability resulting from a re-injury to or aggravation of a previous injury or preexisting condition) shall not be subject to the special procedure set forth in Section 7(a) above, but rather shall be processed and determined in the same manner as any other Grievance under Sections 2-6 above.

## Special Procedure with Respect to Player Discipline.

(a) Any dispute involving (i) a fine or suspension imposed upon a player by the Commissioner (or his designee) for conduct on the playing court (regardless of its financial impact on the player), or (ii) action taken by the Commissioner (or his designee) concerning the preservation of the integrity of, or the maintenance of public confidence in, the game of basketball resulting in a financial impact to the player of \$25,000 or less, shall be processed exclusively as follows:
    (i) Within twenty (20) days following written notification of the action taken by the Commissioner (or his designee), a player affected thereby or the Players Association may appeal in writing to the Commissioner.
    (ii) Upon the written request of the Players Association, the Commissioner shall designate a time and place for hearing as soon as is reasonably practicable following his receipt of the notice of appeal.
    (iii) As soon as reasonably practicable, but not later than twenty (20) days, following the conclusion of such hearing, the Commissioner shall render a written decision, which decision shall constitute full, final and complete disposition of the dispute, and shall be binding upon the player(s) and Team(s) involved and the parties to this Agreement.
    (iv) In the event such appeal involves a fine or suspension imposed by the Commissioner's designee, the Commissioner, as a consequence of such appeal and hearing, shall have authority only to affirm or reduce such fine or suspension, and shall not have authority to increase such fine or suspension.
(b) In the event a matter filed as a Grievance in accordance with the provisions of Section 2(d) gives rise to issues involving the integrity of, or public confidence in, the game of basketball, and the financial impact on the player of the action being grieved is \$25,000 or less, the Commissioner may, at any stage of its processing, order that the matter be withdrawn from such processing and thereafter be processed in accordance with the procedure provided in Section 8(a).

## Procedure with Respect to Fine and Suspension Amounts.

In the event that a Grievance challenging a Commissioner or Team-imposed fine and/or suspension is filed in accordance with this Article, the amount of any fine or salary lost by virtue of the suspension shall be deposited in a separate interest-bearing account maintained for such fines or suspension-related amounts. The NBA shall provide written notice to the Players Association of the date and amount of each deposit made pursuant to this Section 9, and the custodian of the account shall deliver monthly statements reflecting the investment activity in such account to the NBA and the Players Association. In the absence of agreement between the NBA and the Players Association, the Grievance Arbitrator (in a manner consistent with his determination of a Grievance subject to the provisions of this Section) shall determine the amount of the deposited funds to be payable to the player, the Team, or the NBA, and any interest earned on such deposit shall be allocated to the parties in proportion thereto.

## Disputes with Respect to the Terms of a Player Contract.

(a) If either the NBA or the Players Association asserts that a term or provision of a Player Contract is not permitted by this Agreement, either may have the dispute involving such Contract term or provision resolved by initiating a Grievance. If such a Grievance is initiated by the NBA, the 30-day time period referred to in Section 2(c) of this Article XXXI shall commence with the date upon which the NBA received the Player Contract (or amendment thereto) containing the disputed term or provision. If such a Grievance is initiated by the Players Association, the 30-day time period referred to in Section 2(c) of this Article XXXI shall commence with the date upon which the Player Contract (or amendment thereto) containing the disputed term or provision was first made available for inspection by the Players Association.
(b) If, as a result of the Grievance and Arbitration procedure, a Player Contract is found to contain a term or provision that is not permitted by this Agreement, then (i) such term or provision shall be deleted from the Player Contract and have no force or effect, and the Player Contract shall in all other respects remain valid and binding upon the parties thereto, and (ii) if the Team and the Player agree to reform or revise the Player Contract within 30 days of the Grievance Arbitrator's decision, such reformation or revision shall be exempted from the rules governing Renegotiations contained in Article VII, Section 7(c).
(c) Nothing set forth above shall affect in any manner the Commissioner's authority with respect to the approval or disapproval of Player Contracts pursuant to paragraph 11 of the Uniform Player Contract; and the fact that the Commissioner has approved or not disapproved a Player Contract containing a term or provision not permitted by this Agreement shall not be referred to in the course of the Grievance and Arbitration procedure and shall not be considered in any manner or for any purpose by the Grievance Arbitrator in connection with a dispute concerning that Player Contract.

## Disputes with Respect to Players Under Contract Who Withhold Playing Services.

In addition to any other rights a Team may have under contract or law, including those under paragraph 9 of a Uniform Player Contract, a Team may recover damages in a proceeding before the Grievance Arbitrator when a player who is party to a currently effective Player Contract fails or refuses to render the services called for under the Player Contract. In any such proceeding, where the Grievance Arbitrator determines that damages are continuing to accrue at the time of the hearing, the Arbitrator shall award such damages (if any) as the Team has by then sustained, and the hearing shall remain open to enable the submission of proof on the issue of continuing damages.

## Expedited Procedure.

(a) Notwithstanding the foregoing, in the event of a dispute arising under Article XVII, Article XXX, or Article XXXI, Section 11 of this Agreement, or under paragraph 15 of a Uniform Player Contract (but only insofar as such paragraph provides), or in the event of an alleged breach by a player of paragraph 9 of a Uniform Player Contract, the NBA or the Players Association may request that such dispute or alleged breach be referred immediately to the Grievance Arbitrator. In any such case, the dispute or alleged breach shall be asserted by notice in writing or by facsimile given to the other party or parties, the NBA, the Players Association, and the Grievance Arbitrator.
(b) The Grievance Arbitrator shall convene a hearing with respect to such dispute or alleged breach at the earliest possible time, but in no event later than 24 hours following his receipt of such notice. If the Grievance Arbitrator is not immediately available and the parties are unable to agree upon another grievance arbitrator, the American Arbitration Association shall appoint such other grievance arbitrator.
(c) The award, which shall be issued not later than twenty-four (24) hours after the conclusion of the hearing, shall be in writing and may be issued with or without opinion. If any party desires an opinion, one shall be issued but its issuance shall not delay compliance with or enforcement of the award. The award shall constitute full, final and complete disposition of the dispute or alleged breach, and shall be binding upon the player(s) and Team(s) involved and the parties to this Agreement.
(d) The failure of any party to attend the hearing as scheduled shall not delay the hearing, and the Grievance Arbitrator shall be authorized to proceed to take evidence and issue an award as though such party were present.

## Threshold Amounts for Certain Grievances.

A fine or suspension imposed by a Team shall be appealable to the Grievance Arbitrator only if it results in a financial impact on the player of more than \$2,000. A fine or suspension imposed by the Commissioner shall be appealable to the Grievance Arbitrator only if it results in a financial impact on the player of more than \$25,000.

## Miscellaneous.

(a) Each of the time limits set forth herein may be extended by mutual agreement of the parties involved.
(b) In any meeting or hearing provided for by this Article, a player may be accompanied by a representative of the Players Association who may participate in such meeting or hearing and represent the player. In any such meeting or hearing, the NBA and any Team involved may attend and be accompanied by a representative who may participate in such meeting or hearing and represent the NBA and any such Team.
(c) The parties recognize that a player may be subjected to disciplinary action for just cause by his Team or by the Commissioner (or his designee). Therefore, in Grievances regarding discipline, the issue to be resolved shall be whether there has been just cause for the penalty imposed.
(d) Nothing contained herein shall excuse a player from prompt compliance with any discipline imposed upon him. If discipline imposed upon a player is determined to be improper by a final disposition under this Article XXXI, the player shall promptly be made whole.
(e) Nothing contained in this Article XXXI shall be deemed to limit or impair the right of the NBA or any Team to impose discipline upon a player(s) or to take any other action not inconsistent with the provisions of a Player Contract or this Agreement.
(f) Subject to Section 3(c) above, all costs of arbitration, including the fees and expenses of the Grievance Arbitrator, shall be borne equally by the parties thereto; but each party shall bear the cost of its own witnesses, counsel, and the like.
(g) A Team shall not be required to terminate a Player Contract under the NBA waiver procedure as a condition precedent to the filing of a Grievance with respect to such Player Contract. To the extent that the decision of the Impartial Arbitrator in In re Otis Birdsong, Dec. No. 87-2, May 14, 1987, is inconsistent with the foregoing, it is hereby
overruled.
(h) In a proceeding involving the interpretation of a Player Contract, no Uniform Player Contract (whether signed during the term of this Agreement or during the term of any prior collective bargaining agreement between the parties), or amendment thereto, other than the Player Contract or amendment that is the subject of dispute shall be admissible as evidence of the meaning of, or of the parties' intentions with respect to, any individually negotiated terms or provisions in the Player Contract or amendment that is the subject of dispute.