# INTEGRATION, ENTIRE AGREEMENT, INTERPRETATION, CHOICE OF LAW
\chaptermark{INTEGRATION, ENTIRE AGREEMENT \ldots}

## Integration, Entire Agreement.

This Agreement, together with the exhibits hereto, constitutes the entire understanding between the parties and all understandings, conversations and communications, proposals, and counterproposals, oral and written (including any draft of this Agreement) between the Members of the NBA and the Players Association, or on behalf of them, are merged into and superseded by this Agreement and shall be of no force or effect, except as expressly provided herein. No such understandings, conversations, communications, proposals, counterproposals or drafts shall be referred to in any proceeding by the parties. Further, no understanding contained in this Agreement shall be modified, altered or amended, except by a writing signed by the party against whom enforcement is sought.

## Interpretation.

The NBA and Players Association recognize that this Agreement is separate and distinct from a collective bargaining agreement entered into between WNBA, LLC ("WNBA") and the Women's National Basketball Players Association ("WNBPA"), and intend for this Agreement to be interpreted without reference to the WNBA/WNBPA collective bargaining agreement (or to any other current or prior agreement between the WNBA or WNBAEnterprises, LLC, on the one hand, and the WNBPA on the other), or to any of its or their provisions, or to the fact that a subject was not or is not covered by or included in agreements between the WNBA (or WNBA Enterprises, LLC) and the WNBPA. Accordingly, the parties agree that they will make no reference to any agreement between the WNBA (or WNBA Enterprises, LLC) and the WNBPA or to any provisions thereof (or to the fact that a particular provision was not or is not included in any such agreement), or to any practice or policy of the WNBA (or WNBA Enterprises, LLC) or the WNBPA, in any arbitral, judicial, administrative, or other proceeding, including, without limitation, a proceeding brought under Articles XXXI or XXXII of this Agreement. The parties further agree that no such agreement, provisions (or absence of provisions), practices, or policies may be relied upon by any decisionmaker in such proceedings.

## Choice of Law.

This Agreement is made under and shall be governed by the internal law of the State of New York, except where federal law may govern.