# (APPENDIX) Appendix {-} 

# NATIONAL BASKETBALL ASSOCIATION UNIFORM PLAYER CONTRACT

## 

THIS AGREEMENT made this ___ day of ________, _ is by and between ___________ (hereinafter called the "Team"), a member of the National Basketball Association (hereinafter called the "NBA" or "League") and ___________, an individual whose address is shown below (hereinafter called the "Player"). In consideration of the mutual promises hereinafter contained, the parties hereto promise and agree as follows:

1. TERM.

    The Team hereby employs the Player as a skilled basketball player for a term of ___________ year(s) from the 1st day of ___________ September.

2. SERVICES.

(a) The services to be rendered by the Player pursuant to this Contract shall include: (i) training camp, (ii) practices, meetings, and conditioning sessions conducted by the Team during the Season, (iii) games scheduled for the Team during any Regular Season, (iv) Exhibition games scheduled by the Team or the League during and prior to any Regular Season, (v) the NBA's All-Star Game (including the Rookie Game) and every event conducted in association with such All-Star Game (including, but not limited to, a reasonable number of media sessions and any event that is part of an All-Star Skills Competition if the Player had previously agreed to participate in that Competition), if the Player is invited to participate therein, (vi) Playoff games scheduled by the League subsequent to any Regular Season, and (vii) promotional activities of the Team and the League as set forth in paragraph 13 herein.
(b) If the Player is a Veteran, the Player will not be required to attend training camp earlier than 2 p.m. (local time) on the twenty-ninth (29th) day prior to the first game of any Regular Season. Notwithstanding the foregoing, if the Team is scheduled during a particular NBA Season to participate outside of North America in an Exhibition game or a Regular Season game during the first week of the Regular Season, such Veteran Player may be required to attend the training camp conducted in advance of that Regular Season by 2 p.m. (local time) on the thirty-second (32nd) day prior to the first game of the Regular Season. Rookies may be required to attend training camp at an earlier date, but no earlier than ten (10) days prior to the date that Veterans are required to attend.
(c) Exhibition games shall not be played on the three (3) days prior to the opening of the Team's Regular Season schedule, nor on the day prior to a Regular Season game, nor on the day prior to and the day following the All-Star Game. Exhibition games prior to any Regular Season shall not exceed eight (including intra-squad games for which admission is charged), and Exhibition games during any Regular Season shall not exceed three.

3. COMPENSATION.

(a) Subject to paragraph 3(b) below, the Team agrees to pay the Player for rendering the services described herein the Compensation described in Exhibit 1 or Exhibit 1A hereto (less all amounts required to be withheld by federal, state, and local authorities, and exclusive of any amount(s) which the Player shall be entitled to receive from the Player Playoff Pool). Unless otherwise provided in Exhibit 1, such Compensation shall be paid in twelve (12) equal semi-monthly payments beginning with the first of said payments on November 15th of each year covered by the Contract and continuing with such payments on the first and fifteenth of each month until said Compensation is paid in full.
(b) The Team agrees to pay the Player \$1,500 per week, pro rata, less all amounts required to be withheld by federal, state, and local authorities, for each week (up to a maximum of four (4) weeks for veterans and up to a maximum of five (5) weeks for Rookies) prior to the Team's first Regular Season game that the Player is in attendance at training camp or Exhibition games; provided, however, that no such payments shall be made if, prior to the date on which he is required to attend training camp, the Player has been paid \$10,000 or more in compensation with respect to the NBA Season scheduled to commence immediately following such training camp. Any Compensation paid by the Team pursuant to this subparagraph shall be considered an advance against any Compensation owed to the Player pursuant to paragraph 3(a) above, and the first scheduled payment of such Compensation (or such subsequent payments, if the first scheduled payment is not sufficient) shall be reduced by the amount of such advance.
(c) The Team will not pay and the Player will not accept any bonus or anything of value on account of the Team's winning any particular NBA game or series of games or attaining a certain position in the standings of the League as of a certain date, other than the final standing of the Team.

4. EXPENSES.

    The Team agrees to pay all proper and necessary expenses of the Player, including the reasonable lodging expenses of the Player while playing for the Team "on the road" and during the training camp period (defined for this paragraph only to mean the period from the first day of training camp through the day of the Team's first Exhibition game) for as long as the Player is not then living at home. The Player, while "on the road" (and during the training camp period, only if the player is not then living at home and the Team does not pay for meals directly), shall be paid a meal expense allowance as set forth in the Collective Bargaining Agreement currently in effect between the NBA and the National Basketball Players Association (hereinafter "the NBA/NBPA Collective Bargaining Agreement"). No deductions from such meal expense allowance shall be made for meals served on an airplane. During the training camp period (and only if the player is not then living at home and the Team does not pay for meals directly), the meal expense allowance shall be paid in weekly installments commencing with the first week of training camp. For the purposes of this paragraph, the Player shall be considered to be "on the road" from the time the Team leaves its home city until the time the Team arrives back at its home city.

5. CONDUCT.

(a) The Player agrees to observe and comply with all Team rules, as maintained or promulgated in accordance with the NBA/NBPA Collective Bargaining Agreement, at all times whether on or off the playing floor. Subject to the provisions of the NBA/NBPA Collective Bargaining Agreement, such rules shall be part of this Contract as fully as if herein written and shall be binding upon the Player.
(b) The Player agrees (i) to give his best services, as well as his loyalty, to the Team, and to play basketball only for the Team and its assignees; (ii) to be neatly and fully attired in public; (iii) to conduct himself on and off the court according to the highest standards of honesty, citizenship, and sportsmanship; and (iv) not to do anything that is materially detrimental or materially prejudicial to the best interests of the Team or the League.
(c) For any violation of Team rules, any breach of any provision of this Contract, or for any conduct impairing the faithful and thorough discharge of the duties incumbent upon the Player, the Team may reasonably impose fines and/or suspensions on the Player in accordance with the terms of the NBA/NBPA Collective Bargaining Agreement.
(d) The Player agrees to be bound by Article 35 of the NBA Constitution, a copy of which, as in effect on the date of this Contract, is attached hereto. The Player acknowledges that the Commissioner is empowered to impose fines upon and/or suspend the Player for causes and in the manner provided in such Article, provided that such fines and/or suspensions are consistent with the terms of the NBA/NBPA Collective Bargaining Agreement.
(e) The Player agrees that if the Commissioner, in his sole judgment, shall find that the Player has bet, or has offered or attempted to bet, money or anything of value on the outcome of any game participated in by any team which is a member of the NBA, the Commissioner shall have the power in his sole discretion to suspend the Player indefinitely or to expel him as a player for any member of the NBA, and the Commissioner's finding and decision shall be final, binding, conclusive, and unappealable.
(f) The Player agrees that he will not, during the term of this Contract, directly or indirectly, entice, induce, or persuade, or attempt to entice, induce, or persuade, any player or coach who is under contract to any NBA team to enter into negotiations for or relating to his services as a basketball player or coach, nor shall he negotiate for or contract for such services, except with the prior written consent of such team. Breach of this subparagraph, in addition to the remedies available to the Team, shall be punishable by fine and/or suspension to be imposed by the Commissioner.
(g) When the Player is fined and/or suspended by the Team or the NBA, he shall be given notice in writing (with a copy to the Players Association), stating the amount of the fine or the duration of the suspension and the reasons therefor.

6. WITHHOLDING.

(a) In the event the Player is fined and/or suspended by the Team or the NBA, the Team shall withhold the amount of the fine or, in the case of a suspension, the amount provided in Article VI of the NBA/NBPA Collective Bargaining Agreement from any Current Cash Compensation due or to become due to the Player with respect to the contract year in which the conduct resulting in the fine and/or the suspension occurred (or a subsequent contract year if the Player has received all Current Cash Compensation due to him for the then current contract year). If, at the time the Player is fined and/or suspended, the Current Cash Compensation remaining to be paid to the Player under this Contract is not sufficient to cover such fine and/or suspension, then the Player agrees promptly to pay the amount directly to the Team. In no case shall the Player permit any such fine and/or suspension to be paid on his behalf by anyone other than himself.
(b) Any Current Cash Compensation withheld from or paid by the Player pursuant to this paragraph 6 shall be retained by the Team or the League, as the case may be, unless the Player contests the fine and/or suspension by initiating a timely Grievance in accordance with the provisions of the NBA/NBPA Collective Bargaining Agreement. If such Grievance is initiated and it satisfies Article XXXI, Section 13 of the NBA/NBPA Collective Bargaining Agreement, the amount withheld from the Player shall be placed in an interest-bearing account, pursuant to Article XXXI, Section 9 of such Agreement, pending the resolution of the Grievance.

7. PHYSICAL CONDITION.

(a) The Player agrees to report at the time and place fixed by the Team in good physical condition and to keep himself throughout each NBA Season in good physical condition.
(b) If the Player, in the judgment of the Team's physician, is not in good physical condition at the date of his first scheduled game for the Team, or if, at the beginning of or during any Season, he fails to remain in good physical condition (unless such condition results directly from an injury sustained by the Player as a direct result of participating in any basketball practice or game played for the Team during such Season), so as to render the Player, in the judgment of the Team's physician, unfit to play skilled basketball, the Team shall have the right to suspend such Player until such time as, in the judgment of the Team's physician, the Player is in sufficiently good physical condition to play skilled basketball. In the event of such suspension, the Compensation (excluding any signing bonus or Incentive Compensation) payable to the Player for any Season during such suspension shall be reduced in the same proportion as the length of the period during which, in the judgment of the Team's physician, the Player is unfit to play skilled basketball, bears to the length of such Season.
(c) If, during the term of this Contract, the Player is injured as a direct result of participating in any basketball practice or game played for the Team, the Team will pay the Player's reasonable hospitalization and medical expenses (including doctor's bills), provided that the hospital and doctor are selected by the Team, and provided further that the Team shall be obligated to pay only those expenses incurred as a direct result of medical treatment caused solely by and relating directly to the injury sustained by the Player. Subject to the provisions set forth in Exhibit 3, if in the judgment of the Team's physician, the Player's injuries resulted directly from playing for the Team and render him unfit to play skilled basketball, then, so long as such unfitness continues, but in no event after the Player has received his full Compensation for the Season in which the injury was sustained, the Team shall pay to the Player the Compensation prescribed in Exhibit 1 to this Contract for such Season. The Team's obligations hereunder shall be reduced by (i) any workers' compensation benefits, which, to the extent permitted by law, the Player hereby assigns to the Team, and (ii) any insurance provided for by the Team whether paid or payable to the Player.
(d) The Player agrees to provide to the Team's coach, trainer, or physician prompt notice of any injury, illness, or medical condition suffered by him that is likely to affect adversely the Player's ability to render the services required under this Contract, including the time, place, cause, and nature of such injury, illness, or condition.
(e) Should the Player suffer an injury, illness, or medical condition as provided in this paragraph 7, he will submit himself to a medical examination and appropriate medical treatment by a physician designated by the Team. Such examination when made at the request of the Team shall be at its expense, unless made necessary by some act or conduct of the Player contrary to the terms of this Contract.

8. PROHIBITED SUBSTANCES.

    The Player acknowledges that this Contract may be terminated in accordance with the express provisions of Article XXXIII (Anti-Drug Program) of the NBA/NBPA Collective Bargaining Agreement, and that any such termination will result in the Player's immediate dismissal and disqualification from any employment by the NBA and any of its teams. Notwithstanding any terms or provisions of this Contract (including any amendments hereto), in the event of such termination, all obligations of the Team, including obligations to pay Compensation, shall cease, except the obligation of the Team to pay the Player's earned Compensation (whether Current or Deferred) to the date of termination.

9. UNIQUE SKILLS.

    The Player represents and agrees that he has extraordinary and unique skill and ability as a basketball player, that the services to be rendered by him hereunder cannot be replaced or the loss thereof adequately compensated for in money damages, and that any breach by the Player of this Contract will cause irreparable injury to the Team, and to its assignees. Therefore, it is agreed that in the event it is alleged by the Team that the Player is playing, attempting or threatening to play, or negotiating for the purpose of playing, during the term of this Contract, for any other person, firm, corporation, or organization, the Team and its assignees (in addition to any other remedies that may be available to them judicially or by way of arbitration) shall have the right to obtain from any court or arbitrator having jurisdiction such equitable relief as may be appropriate, including a decree enjoining the Player from any further such breach of this Contract, and enjoining the Player from playing basketball for any other person, firm, corporation, or organization during the term of this Contract. The Player agrees that the Team may at any time assign such right to the NBA for the enforcement thereof. In any suit, action, or arbitration proceeding brought to obtain such equitable relief, the Player does hereby waive his right, if any, to trial by jury, and does hereby waive his right, if any, to interpose any counterclaim or set-off for any cause whatever.

10. ASSIGNMENT.

(a) The Team shall have the right to assign this Contract to any other NBA team and the Player agrees to accept such assignment and to faithfully perform and carry out this contract with the same force and effect as if it had been entered into by the Player with the assignee team instead of with the Team. The Player further agrees that, should the Team contemplate the assignment of this Contract to one or more NBA teams, the Team's physician may furnish to the physicians and officials of such other team or teams all relevant medical information relating to the Player.
(b) In the event that this Contract is assigned to any other NBA team, all reasonable expenses incurred by the Player in moving himself and his family to the home territory of the team to which such assignment is made, as a result thereof, shall be paid by the assignee team. Such assignee team hereby agrees that its acceptance of the assignment of this Contract constitutes agreement on its part to make such payment.
(c) In the event that this Contract is assigned to another NBA team, the Player shall forthwith be provided notice orally or in writing, delivered to the Player personally or delivered or mailed to his last known address, and the Player shall report to the assignee team within forty-eight (48) hours after said notice has been received (if the assignment is made during a Season), within one (1) week after said notice has been received (if the assignment is made between Seasons), or within such longer time for reporting as may be specified in said notice. The NBA shall also promptly notify the Players Association of any such assignment. The Player further agrees that, immediately upon reporting to the assignee team, he will submit upon request to a physical examination conducted by a physician designated by the assignee team.
(d) If the Player, without a reasonable excuse, does not report to the team to which this Contract has been assigned within the time provided in subsection (c) above, then, upon consummation of the assignment, the player may be suspended by the assignee team or, if the assignment is not consummated or is voided as a result of the Player's failure to so report, by the assignor Team. In either case, the Player's Compensation may be reduced by the NBA by the imposition of a fine in an amount equal to the lesser of (i) ten (10) percent of the Player's full Compensation for the then-current Season, or (ii) \$50,000.

11. VALIDITY AND FILING.

(a) This Contract shall be valid and binding upon the Team and the Player immediately upon its execution.
(b) The Team agrees to file a copy of this Contract, and/or any amendment(s) thereto, with the Commissioner of the NBA as soon as practicable by facsimile and overnight mail, but in no event may such filing be made more than forty-eight (48) hours after the execution of this Contract and/or amendment(s).
(c) If pursuant to the NBA Constitution and By-Laws or the NBA/NBPA Collective Bargaining Agreement, the Commissioner disapproves this Contract (or amendment) within ten (10) days after the receipt thereof in his office by overnight mail, this Contract (or amendment) shall thereupon terminate and be of no further force or effect and the Team and the Player shall thereupon be relieved of their respective rights and liabilities thereunder. If the Commissioner's disapproval is subsequently overturned in any proceeding brought under the arbitration provisions of the NBA/NBPA Collective Bargaining Agreement (including any appeals), the Contract shall again be valid and binding upon the Team and the Player, and the Commissioner shall be afforded another ten-day period to disapprove the Contract (based on the Team's Room at the time the Commissioner's disapproval is overturned) as set forth in the foregoing sentence. The NBA will promptly inform the Players Association if the Commissioner disapproves this Contract.

12. OTHER ATHLETIC ACTIVITIES.

    The Player and the Team acknowledge and agree that (i) the Player's participation in other sports may impair or destroy his ability and skill as a basketball player, and (ii) the Player's participation in basketball out of season may result in injury to him. Accordingly, the Player agrees that he will not, without the written consent of the Team, engage in (x) sports endangering his health or safety (including,but not limited to, professional boxing or wrestling, motorcycling, moped-riding, auto racing, sky-diving, and hang gliding), or (y) any game or exhibition of basketball, football, baseball, hockey, lacrosse, or other athletic sport, under penalty of such fine and/or suspension as may be imposed by the Team and/or the Commissioner of the NBA. Nothing contained herein shall be intended to require the Player to obtain the written consent of the Team in order to enable the Player to participate in, as an amateur, the sport of golf, tennis, handball, swimming, hiking, softball, or volleyball.

13. PROMOTIONAL ACTIVITIES.

(a) The Player agrees to allow the Team or the League to take pictures of the Player, alone or together with others, for still photographs, motion pictures, or television, at such times as the Team or the League may designate. No matter by whom taken, such pictures may be used in any manner desired by either the Team or the League for publicity or promotional purposes. The rights in any such pictures taken by the Team or by the League shall belong to the Team or to the League, as their interests may appear.
(b) The Player agrees that, during any year of this Contract, he will not make public appearances, participate in radio or television programs, permit his picture to be taken, write or sponsor newspaper or magazine articles, or sponsor commercial products without the written consent of the Team, which shall not be withheld except in the reasonable interests of the Team or the NBA.
(c) Upon request, the Player shall consent to and make himself available for interviews by representatives of the media conducted at reasonable times.
(d) In addition to the foregoing, and subject to the conditions and limitations set forth in Article II, Section 8 of the NBA/NBPA Collective Bargaining Agreement, the Player agrees to participate, upon request, in all other reasonable promotional activities of the Team and the NBA. For each such promotional appearance made on behalf of a commercial sponsor of the Team, the Team agrees to pay the Player \$1,000 or, if the Team agrees, such higher amount that is consistent with the Team's past practice and not otherwise unreasonable.

14. GROUP LICENSE.

(a) The Player hereby grants to NBA Properties, Inc. the exclusive rights to use the Player's Player Attributes as such term is defined and for such group licensing purposes as are set forth in the Agreement between NBA Properties, Inc. and the National Basketball Players Association, made as of September 18, 1995 and amended January 20, 1999 (the "Group License"), a copy of which will, upon his request, be furnished the Player; and the Player agrees to make the appearances called for by such Agreement.
(b) Notwithstanding anything to the contrary contained in the Group License or this Contract, NBA Properties may use, in connection with League Promotions, the Player's (i) name or nickname and/or (ii) the Player's Player Attributes (as defined in the Group License) as such Player Attributes may be captured in game action footage or photographs. NBA Properties shall be entitled to use the Player's Player Attributes individually pursuant to the preceding sentence and shall not be required to use the Player's Player Attributes in a group or as one of multiple players. As used herein, League Promotion shall mean any advertising, marketing, or collateral materials or marketing programs conducted by the NBA, NBA Properties (or any subsidiary of NBA Properties) or any NBA team that is intended to promote (x) any game in which an NBA team participates or game telecast or broadcast (including Pre-Season, Exhibition, Regular Season, and Playoff games), (y) the NBA, its teams, or its players, or (z) the sport of basketball.

15. TEAM DEFAULT.

    In the event of an alleged default by the Team in the payments to the Player provided for by this Contract, or in the event of an alleged failure by the Team to perform any other material obligation that it has agreed to perform hereunder, the Player shall notify both the Team and the League in writing of the facts constituting such alleged default or alleged failure. If neither the Team nor the League shall cause such alleged default or alleged failure to be remedied within five (5) days after receipt of such written notice, the National Basketball Players Association shall, on behalf of the Player, have the right to request that the dispute concerning such alleged default or alleged failure be referred immediately to the Grievance Arbitrator in accordance with the provisions of the NBA/NBPA Collective Bargaining Agreement. If, as a result of such arbitration, an award issues in favor of the Player, and if neither the Team nor the League complies with such award within ten (10) days after the service thereof, the Player shall have the right, by a further written notice to the Team and the League, to terminate this Contract.

16. TERMINATION.

(a) The Team may terminate this Contract upon written notice to the Player if the Player shall:
    (i) at any time, fail, refuse, or neglect to conform his personal conduct to standards of good citizenship, good moral character (defined here to mean not engaging in acts of moral turpitude, whether or not such acts would constitute a crime), and good sportsmanship, to keep himself in first class physical condition, or to obey the Team's training rules; or
    (ii) at any time commit a significant and inexcusable physical attack against any official or employee of the Team or the NBA (other than another player), or any person in attendance at any NBA game or event, considering the totality of the circumstances, including (but not limited to) the degree of provocation (if any) that may have led to the attack, the nature and scope of the attack, the player's state of mind at the time of the attack, and the extent of any injury resulting from the attack; or
    (iii) at any time, fail, in the sole opinion of the Team's management, to exhibit sufficient skill or competitive ability to qualify to continue as a member of the Team; provided, however, (x) that if this Contract is terminated by the Team, in accordance with the provisions of this subparagraph, prior to January 10 of any Regular Season, and the Player, at the time of such termination, is unfit to play skilled basketball as the result of an injury resulting directly from his playing for the Team, the Player shall (subject to the provisions set forth in Exhibit 3) continue to receive his full Compensation, less all workers' compensation benefits (which, to the extent permitted by law, and if not deducted from the Player's Compensation by the Team, the Player hereby assigns to the Team) and any insurance provided for by the Team paid or payable to the Player by reason of said injury, until such time as the Player is fit to play skilled basketball, but not beyond the Season during which such termination occurred; and provided, further, (y) that if this Contract is terminated by the Team, in accordance with the provisions of this subparagraph, during the period from the January 10 of any Regular Season through the end of such Regular Season, the Player shall be entitled to receive his full Compensation for said Season; or
    (iv) at any time, fail, refuse, or neglect to render his services hereunder or in any other manner materially breach this Contract.
(b) If this Contract is terminated by the Team by reason of the Player's failure to render his services hereunder due to disability caused by an injury to the Player resulting directly from his playing for the Team and rendering him unfit to play skilled basketball, and notice of such injury is given by the Player as provided herein, the Player shall (subject to the provisions set forth in Exhibit 3) be entitled to receive his full Compensation for the Season in which the injury was sustained, less all workers' compensation benefits (which, to the extent permitted by law, and if not deducted from the Player's Compensation by the Team, the Player hereby assigns to the Team) and any insurance provided for by the Team paid or payable to the Player by reason of said injury.
(c) Notwithstanding the provisions of subparagraph 16(b) above, if this Contract is terminated by the Team prior to the first game of a Regular Season by reason of the Player's failure to render his services hereunder due to an injury or condition sustained or suffered during a preceding Season, or after such Season but prior to the Player's participation in any basketball practice or game played for the Team, payment by the Team of any Compensation earned through the date of termination under paragraph 3(b) above, payment of the Player's board, lodging, and expense allowance during the training camp period, payment of the reasonable traveling expenses of the Player to his home city, and the expert training and coaching provided by the Team to the Player during the training season shall be full payment to the Player.
(d) If this Contract is terminated by the Team during the period designated by the Team for attendance at training camp, payment by the Team of any Compensation earned through the date of termination under paragraph 3(b) above, payment of the Player's board, lodging, and expense allowance during such period to the date of termination, payment of the reasonable traveling expenses of the Player to his home city, and the expert training and coaching provided by the Team to the Player during the training season shall be full payment to the Player.
(e) If this Contract is terminated by the Team after the first game of a Regular Season, except in the case provided for in subparagraphs (a)(iii) and (b) of this paragraph 16, the Player shall be entitled to receive as full payment hereunder a sum of money which, when added to the salary which he has already received during such Season, will represent the same proportionate amount of the annual sum set forth in Exhibit 1 hereto as the number of days of such Regular Season then past bears to the total number of days of such Regular Season, plus the reasonable traveling expenses of the Player to his home.
(f) If the Team proposes to terminate this Contract in accordance with subparagraph (a) of this paragraph 16, it must first comply with the following waiver procedure:
    (i) The Team shall request the NBA Commissioner to request waivers from all other clubs. Such waiver request may not be withdrawn.
    (ii) Upon receipt of the waiver request, any other team may claim assignment of this Contract at such waiver price as may be fixed by the League, the priority of claims to be determined in accordance with the NBA Constitution and By-Laws.
    (iii) If this Contract is so claimed, the Team agrees that it shall, upon the assignment of this Contract to the claiming team, notify the Player of such assignment as provided in paragraph 10(c) hereof, and the Player agrees he shall report to the assignee team as provided in said paragraph 10(c).
    (iv) If the Contract is not claimed, the Team shall promptly deliver written notice of termination to the Player at the expiration of the waiver period.
    (v) The NBA shall promptly notify the Players Association of the disposition of any waiver request.
    (vi) To the extent not inconsistent with the foregoing provisions of this subparagraph (f), the waiver procedures set forth in the NBA Constitution and By-Laws, a copy of which, as in effect on the date of this Contract, is attached hereto, shall govern.
(g) Upon any termination of this Contract by the Player, all obligations of the Team to pay Compensation shall cease on the date of termination, except the obligation of the Team to pay the Player's Compensation to said date.

17. DISPUTES.

    In the event of any dispute arising between the Player and the Team relating to any matter arising under this Contract, or concerning the performance or interpretation thereof (except for a dispute arising under paragraph 9 hereof), such dispute shall be resolved in accordance with the Grievance and Arbitration Procedure set forth in the NBA/NBPA Collective Bargaining Agreement.

18. PLAYER NOT A MEMBER.

    Nothing contained in this Contract or in any provision of the NBA Constitution and By-Laws shall be construed to constitute the Player a member of the NBA or to confer upon him any of the rights or privileges of a member thereof.

19. RELEASE.

    The Player hereby releases and waives every claim he may have against the NBA and its related entities and every member of the NBA, and against every director, officer, owner, stockholder, trustee, partner, and employee of the NBA and its related entities and/or any member of the NBA and their related entities (excluding persons employed as players by any such member), and against any person retained by the NBA and/or the Players Association in connection with the NBA/NBPA Anti-Drug Program, the Grievance Arbitrator, the System Arbitrator, and any other arbitrator or expert retained by the NBA and/or the Players Association under the terms of the NBA/NBPA Collective Bargaining Agreement, arising out of or in connection with (i) any injury that is subject to the provisions of paragraph 7, (ii) any fighting or other form of violent and/or unsportsmanlike conduct occurring during the course of any practice and/or any Exhibition, Regular Season, and/or Playoff game (on or adjacent to the playing floor or in or adjacent to any facility used for practices or games), (iii) the testing procedures or the imposition of any penalties set forth in paragraph 8 hereof and in the NBA/NBPA Anti-Drug Program, or (iv) any injury suffered in the course of his employment as to which he has or would have a claim for workers' compensation benefits. The foregoing shall not apply to any claim of medical malpractice against a Team-affiliated physician or other medical personnel.

20. ENTIRE AGREEMENT.

    This Contract (including any Exhibits hereto) contains the entire agreement between the parties and sets forth all components of the Player's Compensation from the Team or any Team Affiliate, and there are no undisclosed agreements of any kind, express or implied, oral or written, promises, undertakings, representations, commitments, inducements, assurances of intent, or understandings of any kind that have not been disclosed to the NBA (a) involving consideration of any kind to be paid, furnished, or made available to the Player, or any person or entity controlled by or related to the Player, by the Team or any Team Affiliate, either during the term of this Contract or thereafter, or (b) concerning any future Renegotiation, Extension, or other amendment of this Contract or the entry into any new Player Contract.

\newpage

EXAMINE THIS CONTRACT CAREFULLY BEFORE SIGNING IT.

THIS CONTRACT INCLUDES EXHIBITS __________, WHICH ARE ATTACHED HERETO AND MADE A PART HEREOF.

IN WITNESS WHEREOF the Player has hereunto signed his name and the Team has caused this Contract to be executed by its duly authorized officer.

WITNESSES:  

|                              |                                      |
| :--------------------------- | :----------------------------------- |
| Dated: _____________________ | By:     ____________________________ |
|                              | Title:  ____________________________ |
|                              | Team:   ____________________________ |
|                              |                                      |
| Dated: _____________________ | By:     ____________________________ |
|                              | Player: ____________________________ |
|                              | Player's Address:                    |
|                              | ____________________________________ |
|                              | ____________________________________ |

\newpage


### EXCERPT FROM NBA CONSTITUTION

#### MISCONDUCT

35. The provisions of this Article 35 shall govern all Players in the Association, hereinafter referred to as "Players."
    (a) Each Member shall provide and require in every contract with any of its Players that they shall be bound and governed by the provisions of this Article. Each Member, at the direction of the Board of Governors or the Commissioner, as the case may be, shall take such action as the Board or the Commissioner may direct in order to effectuate the purposes of this Article.
    (b) The Commissioner shall direct the dismissal and perpetual disqualification from any further association with the Association or any of its Members, of any Player found by the Commissioner after a hearing to have been guilty of offering, agreeing, conspiring, aiding or attempting to cause any game of basketball to result otherwise than on its merits.
    (c) Any Player who gives, makes, issues, authorizes or endorses any statement having, or designed to have, an effect prejudicial or detrimental to the best interests of basketball or of the Association or of a Member or its Team, shall be liable to a fine not exceeding \$25,000, to be imposed by the Commissioner. The Member whose Player has been so fined shall pay the amount of the fine should such Player fail to do so within ten (10) days of its imposition.
    (d) If in the opinion of the Commissioner any other act or conduct of a Player at or during an Exhibition, Regular Season, or Playoff game has been prejudicial to or against the best interests of the Association or the game of basketball, the Commissioner shall impose upon such Player a fine not exceeding \$35,000, or may order for a time the suspension of any such Player from any connection or duties with Exhibition, Regular Season, or Playoff games, or he may order both such fine and suspension.
    (e) The Commissioner shall have the power to suspend for a definite or indefinite period, or to impose a fine not exceeding \$35,000, or inflict both such suspension and fine upon any Player who, in his opinion, shall have been guilty of conduct that does not conform to standards of morality or fair play, that does not comply at all times with all federal, state, and local laws, or that is prejudicial or detrimental to the Association.
    (f) Any Player who, directly or indirectly, entices, induces, persuades or attempts to entice, induce, or persuade any Player, Coach, Trainer, General Manager or any other person who is under contract to any other Member of the Association to enter into negotiations for or relating to his services or negotiates or contracts for such services shall, on being charged with such tampering, be given an opportunity to answer such charges after due notice and the Commissioner shall have the power to decide whether or not the charges have been sustained; in the event his decision is that the charges have been sustained, then the Commissioner shall have the power to suspend such Player for a definite or indefinite period, or to impose a fine not exceeding \$35,000, or inflict both such suspension and fine upon any such Player.
    (g) Any Player who, directly or indirectly, wagers money or anything of value on the outcome of any game played by a Team in the league operated by the Association shall, on being charged with such wagering, be given an opportunity to answer such charges after due notice, and the decision of the Commissioner shall be final, binding and conclusive and unappealable. The penalty for such offense shall be within the absolute and sole discretion of the Commissioner and may include a fine, suspension, expulsion and/or perpetual disqualification from further association with the Association or any of its Members.
    (h) Except for a penalty imposed under Paragraph (g) of this Article 35, any challenge by a Team to the decisions and acts of the Commissioner pursuant to Article 35 shall be appealable to the Board of Governors who shall determine such appeals in accordance with such rules and regulations as may be adopted by the Board in its absolute and sole discretion. Any such challenge by a player shall be resolved by the Grievance Arbitrator in accordance with the grievance and arbitration procedures of the collective bargaining agreement then in effect.

\newpage


### EXCERPT FROM NBABY-LAWS

5.01. *Waiver Right.* Except for sales and trading between Members in accordance with these By-Laws, no Member shall sell, option, or otherwise assign the contract with, right to the services of, or right to negotiate with, a Player without complying with the waiver procedure prescribed by this Constitution and By-Laws.
5.02. *Waiver Price.* The waiver price shall be \$1,000 per Player.
5.03. *Waiver Procedure.* A Member desiring to secure waivers on a Player shall notify the Commissioner or the Commissioner's designee, who shall, on behalf of such Member, immediately notify all other Members of the waiver request. Such Player shall be assumed to have been waived unless a Member shall notify the Commissioner or the Commissioner's designee in accordance with Section 5.04 of a claim to the rights to such Player. Once a Member has notified the Commissioner or the Commissioner's designee of its desire to secure waivers on a Player, such notice may not be withdrawn. A Player remains the financial responsibility of the Member placing him on waivers until the waiver period set by the Commissioner or the Commissioner's designee has expired.
5.04. *Waiver Period.* If the Commissioner or the Commissioner's designee distributes notice of request for waiver at any time between August 15 and the end of the next Season, any Members wishing to claim rights to the Player shall do so by giving notice by telephone and in a Writing of such claim to the Commissioner or the Commissioner's designee within forty-eight (48) hours after the time of such notice. If the Commissioner or the Commissioner's designee distributes notice of request for waiver at any other time, any Member wishing to claim rights to the Player shall do so by providing Written Notice of such claim to the Commissioner or the Commissioner's designee within ten (10) days after the date of such notice. A Team may not withdraw a claim to the rights to a Player on waivers.
5.05. *Waiver Preferences.*
    (a) In the event that more than one (1) Member shall have claimed the rights to a Player placed on waivers, the claiming Member with the lowest team standing at the time the waiver was requested shall be entitled to acquire the rights to such Player. If the request for waiver shall occur after the last day of the Season and before 11:59 p.m. eastern time on the following November 30, the standings at the close of the previous Season shall govern.
    (b) If the winning percentage of two (2) claiming Teams are the same, then the tie shall be determined, if possible, on the basis of the Regular Season Games between the two (2) Teams during the Season or during the preceding Season, as the case may be. If still tied, a toss of a coin shall determine priority. For the purpose of determining standings, both Conferences of the Association shall be deemed merged and a consolidated standing shall control.
5.06. *Players Acquired Through Waivers.* A Member who has acquired the rights and title to the contract of a Player through the waiver procedure may not sell or trade such rights for a period of thirty (30) days after the acquisition thereof; provided, however, that if the rights to such Player were acquired between Seasons, the 30-day period described herein shall begin on the first day of the next succeeding Season.5.07. Additional Waiver Rules. The Commissioner or the Board of Governors may from time to time adopt additional rules (supplementary to those set forth in this Section 5) with respect to the operation of the waiver procedure. Such rules shall not be inconsistent with the provisions of this Section 5 and shall apply to but shall not be limited to the mechanics of notice, inadvertent omission of notification to a Member, and rules of construction as to time.

\newpage


### AGENT CERTIFICATION

(To be completed only if Player was represented by an agent who negotiated the terms of this Contract.)

I, the undersigned, having negotiated this Contract on behalf of _________________, do hereby swear and certify, under penalties of perjury, that the terms of Paragraph 20 of this Contract ("Entire Agreement") are true and correct to the best of my knowledge and belief.

|                                          |
| :----------------------------------------|
| Player Representative: _________________ |
| State of _______________________________ |
| County of ______________________________ |

On _____________________, before me personally came _____________________ and acknowledged to me that he/she had executed the foregoing Agent Certification.

|                                          |
| :----------------------------------------|
| Notary Public: ________________________  |

\newpage


## UNIFORM PLAYER CONTRACT

### Exhibit 1 — Compensation

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |


| <u>Season</u> | <u>Current Base Compensation</u> | <u>Deferred Base Compensation</u> |
| :----: | :-----------------------: | :-----------------------: |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |

**Payment Schedule** (if different from paragraph 3):

  Current Base:

  Deferred Base:


**Signing Bonus** (include dates of payment):

**Non-Cash Compensation** (include dates of payment):

**Incentive Compensation** (include dates of payment):

**Other Arrangements:**



| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


#### Exhibit 1A — Compensation: Minimum Player Salary

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |


| <u>Season</u> | <u>Current Base Compensation</u> | <u>Deferred Base Compensation</u> |
| :----: | :-----------------------: | :-----------------------: |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |
| ________ | _______________________ | _________________________ |

**This Contract is intended to provide for a Salary for the _______________________ Season(s) equal to the Minimum Player Salary for such Season(s) (with no Unlikely Bonuses) and shall be deemed amended to the extent necessary to so provide.**

**Payment Schedule** (if different from paragraph 3):

  Current Base:

  Deferred Base:


**Signing Bonus** (include dates of payment):

**Non-Cash Compensation** (include dates of payment):

**Other Arrangements:**



| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage 


### Exhibit 2 — Compensation Protection or Insurance

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

| Season | Type of Protection | Amount of Protection or Insurance | Conditions or Limitations |
| :---: | :-------------: | :---------------: | :-----------------------: |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |
| _____ | ___________ | _______________ | __________________ |

| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 3 — Prior Injury Exclusion

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

The Player's right to receive his Compensation as set forth in paragraphs 7(c), 16(a)(iii), 16(b) of this Contract, or otherwise is limited or eliminated with respect to the following reinjury of the injury or aggravation of the condition set forth below:

| Describe injury or condition:                                 |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Describe the extent to which liability for Compensation is limited or eliminated: |
| :---------------------------------------------------------------------------------------- |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 4 — Assignment Payments

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

In the event this Contract is traded by the Team executing the Contract to another NBA Team, the Player shall be entitled to receive from the assignor Team, within thirty (30) days of the date of such trade, the following payment:

|                                                               |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 5 — Other Athletic Activities

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

Notwithstanding the provisions of paragraph 12 of this Contract, the Player and the Team agree that the Player need not obtain the consent of the Team in order to engage in the activities set forth below:

|                                                               |
| :------------------------------------------------------------ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
| _____________________________________________________________ |
  


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 6 — Physical Exam

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

The Player and the Team agree that this Contract will be invalid and of no further force and effect unless the Player passes, in the sole discretion of a physician designated by the Team, a physical examination conducted within seventy-two (72) hours of the execution of this Contract.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 7 — Substitute for UPC Paragraph 7(b)

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

Paragraph 7(b) is hereby deleted and the following shall be substituted in place and instead thereof:

"7. (b) The Player agrees, notwithstanding any other provision of this Contract, that he will to the best of his ability maintain himself in physical condition sufficient to play skilled basketball at all times. If the Player, in the reasonable judgment of the physician designated for that purpose by the Team, is not in good physical condition at the date of his first scheduled game for the Team, or if, at the beginning of or during any Season, he fails to remain in good physical condition, in either event so as to render the Player unfit in the reasonable judgment of said physician to play skilled basketball, the Team shall have the right to suspend the Player for a period of one (1) week. At the end of such one-week period, should the Team notify the Player, orally or in writing, that in its reasonable judgment it believes the Player is still not in good physical condition, the Team shall have the right to suspend the Player for successive one-week periods until the Player, in the reasonable judgment of the Team's physician, is in good physical condition; provided, however, that at the end of each such one-week period of suspension, the Team provides the notice specified above, and provided further that, at the end of any such one-week period and if the player so requests, then the Player shall be examined by a physician or physicians designated for such purpose by the President, or any Vice President if the President is not available, of the American Society of Orthopedic Physicians, or equivalent organization (the "Reviewing Physician"), whose sole judgment concerning the physical condition of the Player to play skilled basketball shall be binding upon the Team and the Player for purposes of this paragraph. The suspension of the Player shall be terminated promptly upon the failure of the Team to give the Player the notice required at the end of the one-week period or upon the finding of said Reviewing Physician that the Player is in physical condition sufficient to play skilled basketball. In the event of a suspension permitted hereunder, the Compensation (excluding any signing bonus or Incentive Compensation) payable to the Player for any Season during such suspension shall be reduced in the same proportion as the length of the period of disability so determined bears to the length of the Season."

| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |

\newpage


### Exhibit 8 — Sign and Trade

|                                          |
| :----------------------------------------|
| Player: ________________________________ |
| Team: __________________________________ |
| Date: __________________________________ |

The Player and the Team agree that this Contract will be invalid and of no further force and effect unless the Contract is assigned to the [assignee team] within forty-eight (48) hours of its execution, and such assignment is ultimately consummated.


| Initialed:     |                |
| :------------- | :------------- |
| ______________ | ______________ |
| Player         | Team           |
