# NOTICE TO VETERAN PLAYERS CONCERNING SUMMER LEAGUES

An arbitration award issued on June 13, 1977, stated that, in order for an NBA Team to enroll veteran players in a summer pro league, it is necessary for the Team to have such players sign a form signifying that they have chosen to participate in the league on a voluntary basis, and to inform such players of certain provisions. Players participating in any summer league shall be informed as to the following:

1. Under the Uniform Player Contract and the Collective Bargaining Agreement between the NBA and the Players Association, the Team cannot require players to participate in any summer league.
2. The failure of a player to sign such a form to participate in any summer league will not, by itself, prejudice or disadvantage such player in his Team standing or relationship.
3. The Team reserves the right to determine how many and which players it may enroll in any summer league.

We would appreciate your signing and returning the attached form to:

|                          |
| :---------------------   |
| _____________________    |
| _____________________    |
| Name of Team             |