#

## EXHIBIT J-1

January 20, 1999  
Mr. G. William Hunter  
Executive Director  
National Basketball Players Association  
1700 Broadway, Suite 1400  
New York, New York 10019  

Dear Billy:

This will confirm our agreement that a team's termination of a Uniform Player Contract by reason of the player's "lack of skill" (under paragraph 16(a)(iii) thereof) shall be interpreted to include a termination based on the team's determination that, in view of the player's level of skill (in the sole opinion of the Team), the Compensation paid (or to be paid) to the player is no longer commensurate with the team's financial plans or needs. This agreement shall not affect any post-termination obligation to pay Compensation that may result from Compensation protection provisions included in a Uniform Player Contract.

If the foregoing coincides with your understanding of our agreement, please sign this letter in the space provided below.

Sincerely,  
/s/ <u>/s/  JEFFREY A. MISHKIN</u>  
Jeffrey A. Mishkin  

AGREED TO AND ACCEPTED:

NATIONAL BASKETBALL PLAYERS ASSOCIATION  
By: /s/ <u>G. WILLIAM HUNTER</u>  
G. William Hunter  
Executive Director  

## EXHIBIT J-2

January 20, 1999  
Mr. G. William Hunter  
Executive Director  
National Basketball Players Association  
1700 Broadway—Suite 1400  
New York, New York 10019  

Dear Billy:

This will confirm our agreement that the attached accounting procedures are the procedures that will be in effect for purposes of Article VII, Section 10 of the Collective Bargaining Agreement entered into on January 20, 1999, unless such procedures shall be modified by agreement of the parties.

If the foregoing coincides with your understanding of our agreement, please sign this letter in the space provided below.

Sincerely,  
/s/ <u>/s/  JEFFREY A. MISHKIN</u>  
Jeffrey A. Mishkin  

AGREED TO AND ACCEPTED:

NATIONAL BASKETBALL PLAYERS ASSOCIATION  
By: /s/ <u>G. WILLIAM HUNTER</u>  
G. William Hunter  
Executive Director  

\newpage

### Minimum Procedures To Be Provided By The Accountants

<u>**General**</u>

- The Audit Report (and any Interim Audit Report or Interim Escrow Audit Report) must be prepared in accordance with the terms of the Collective Bargaining Agreement ("CBA"), which should be reviewed and understood by all auditors.
- The Basketball Related Income Reporting Package and instructions should be reviewed and understood by all auditors.
- All audit workpapers should be made available for review by representatives of the NBA and Players Association prior to issuance of the report.
- A summary of all audit findings (including any unusual or non-recurring transactions) and proposed adjustments must be jointly reviewed with representatives of the NBA and Players Association prior to issuance of the report.
- Any problems or questions raised during the audit should be resolved jointly with representatives of the NBA and Players Association.
- All estimates should be reviewed in accordance with the CBA. Estimates are to be reviewed based upon the previous year's actual results and current year activity. All estimates should be confirmed with third parties when possible.
- Revenue and expense amounts that have been estimated should be reconfirmed with the controller or other team representatives prior to the issuance of the Audit Report on or before July 31.
- Where possible, team and NBA revenues and expenses should be reconciled to audited financial statements.
- All reporting packages and supporting schedules are to be completed in U.S. dollars.
- The Auditors may consider, but are not bound by, the value attributed to or treatment of revenue or expense items in prior years.
- Auditors should be aware of revenues excluded from BRI. The Teams should be instructed to make available to the Auditors all information necessary to determine categories of revenues they have excluded from BRI. All revenues excluded by the Teams or the NBA should be reviewed with both parties to determine proper exclusion. Auditor should perform a review for revenues improperly excluded from, or included in, BRI.

<u>**Team Salaries**</u>

- Trace amounts to the team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Examine an appropriate sample of player contracts, noting agreement of all salary amounts, in accordance with the definition of Salary in the CBA.
- Compare player names with all player lists for the season in question.
- Discuss method used to value non-cash compensation with the controller or other representative of each team and conclude as to its reasonableness.
- Examine trade arrangements to verify that each team has properly recorded its pro rata portion of the players' entire salary based upon roster days, and that any bonuses or salary increases payable to players have been properly accounted for.
- Inquire of controller or other representative of each team if any additional compensation was paid to players and not included on the schedule, whether or not paid for basketball services. Also inquire if any business arrangements were entered into by the team or team affiliate with players or their affiliates, including with retired players who played for the team within the past five (5) years.
- Review performance bonuses to determine whether such bonuses were actually earned for such season.
- Review signing bonuses to determine if they have been allocated over the Compensation Protected years of the contract.
- Confirm that, where provided in the CBA, certain contracts have been averaged.

<u>**Benefits**</u>

- Trace amounts to the team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Investigate variations in amounts from the prior year through discussion with the controller or other representative of the team.
- Review each team's insurance expenses for premium credits (refunds) received from Planet Insurance Ltd. (owned by Teams) and Prudential Insurance (amounts can be obtained from League Office).
- Review League Office supporting documentation with respect to Benefits.

<u>**Basketball Related Income**</u>

- Trace amounts to team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Trace gate receipts to general ledger and test supporting documentation where appropriate.
- Gate receipts should be reviewed and reconciled to League Office gate receipts summary.
- Verify amounts reported as luxury suite revenues with supporting documentation from the entity that sold, leased or licensed such luxury suites.
- Verify amounts reported as complimentary tickets and tickets traded for goods or services with supporting documentation from the team.
- Trace amounts reported for novelties and concessions, game parking, game programs, Team sponsorships and promotions, arena signage and arena club sales to general ledgers and test supporting documentation where appropriate.
- Where reported amounts include proceeds received by a Related Party, verify the amounts reported with supporting documentation from the Related Party.
- Examine the National Television and Cable contracts at the League Office, and agree to amounts reported.
- Review, at League Office, expenses deducted from the National contracts in accordance with the terms of the CBA. Review supporting documentation and test where applicable.
- Examine local television, local cable and local radio contracts. Verify to amounts reported by teams.
- When local broadcast revenues are not verifiable by reviewing a contract, detailed supporting documentation should be reviewed and tested.
- All loans, advances, bonuses, etc. received by the League Office or its teams should be noted in the report and included in BRI where appropriate.
- Schedules of international broadcast, market extension, copyright royalty revenues and expenses should be obtained from the NBA. Schedules should be verified by agreeing to general ledgers and examining supporting documentation where applicable.
- Schedules of revenues and expenses reported by Properties for sponsorship, NBA related revenues from NBA Entertainment, and NBA Special Events should be obtained from the NBA. Schedules should be verified by agreeing to general ledgers and examining supporting documentation where applicable.
- Net exhibition revenues and expenses should be verified to supporting documentation where appropriate.
- All amounts of other revenues should be reviewed for proper inclusion/exclusion in BRI. Test appropriateness of balances where appropriate.
- Determine the ratio of expenses to revenues for those categories of proceeds that come within the provisions of Article VII of the CBA and determine the extent to which expenses should be disallowed, if at all, pursuant to the provisions of that Section.

<u>**Playoff Revenues**</u>

- All sources of playoff revenues and expenses should be verified per the procedure outlined for Basketball Related Income.
- Because of the late timing of the Playoffs, special attention should be given to revenue and expense estimates.
- Playoff gate receipts should be recorded net of admission taxes. Payments made to the Playoff Pool should not be deducted. Odd game payments should not be either deducted by the paying team or recorded by the receiving team.
- Other playoff expenses should be reviewed in accordance with the terms of the CBA.
- Team expenses paid by the League Playoff Pool, including travel expenses, should not be deducted by teams.
- Review League Office supporting documentation as to expenses deducted from the Playoff Pool.

<u>**Questions Concerning Related Party Transactions**</u>

- Review with controller or other representatives of the team the answers to all questions on this schedule.
- Review that appropriate details are provided where requested.
- Prepare summary of all changes.

<u>**List of Related Parties**</u>

- Review with controller or other representatives of the team all information included on the schedule of related entities.
- Prepare a summary of any changes, corrections or additions to the schedule.
- Review supporting details of any changes.